/* cx_art_font.c -- port of tools/extract_font.py.
 *
 * Burnout 3's three compiled-in HUD/menu fonts, out of the XBE image
 * (build/burnout3.elf) -> <out_root>/build/frontend/<name>.png plus the glyph
 * metrics header <out_root>/src/burnout3_font.h.
 *
 * DISCOVERY (docs/RE_FRONTEND.md section 6): the fonts are COMPILED INTO THE
 * EXECUTABLE (.data), each as a font object followed by its texture record +
 * DXT5 bitmap, in the exact texture-record layout static.dat / .txd / .bgv
 * use (name at +0x48, fmt at +0x34).
 *
 *   * FUN_0002ef90 (font-system init) stores three font-object pointers from
 *     .data and binds each to its texture BY NAME via FUN_0002ddf0 (a
 *     __stricmp scan of a texture container's records at +0x48).  The names
 *     -- "GlobalFont", "HeadFont", "SmallFont" -- exist in no shipped data
 *     file; the only records carrying them are these .data records.      [C]
 *   * Pointer slots: [0x3e7b98] -> GlobalFont, [0x3e7bb0] -> HeadFont,
 *     [0x3e7ba4] -> SmallFont.                                           [C]
 *   * Font object (proven by FUN_001c1060 / FUN_001c0f50's glyph walk and
 *     FUN_0002ef90's relocation loop):
 *       +0x00 char[4] "3rev"      +0x04 u32 texture handle (runtime)
 *       +0x08 f32,f32 layout scale  +0x10 f32,f32 (unresolved scalars)
 *       +0x18 u32 relocated flag    +0x1C ptr default glyph record
 *       +0x20 ptr[128] charmap: glyph record for (c & 0x7F)
 *     Before relocation +0x1C/+0x20[] hold OFFSETS from the object base.
 *   * Glyph record, 0x20 bytes:
 *       +0x00 f32 u   +0x04 f32 v   (top-left, / texture size)
 *       +0x08 f32 w   +0x0C f32 h   (extent,   / texture size)
 *       +0x10 f32 xoffset +0x14 f32 yoffset   +0x18 f32 advance
 *       +0x1C u32 charcode
 *     FUN_001c1060 reads +0x1C as the charcode to verify the charmap hit and
 *     walks 0x20-stride sibling records on mismatch.                     [C]
 *
 *   object      VA        texture rec  name        dims     coverage
 *   GlobalFont  0x3c84d8  0x3c9c38     GlobalFont  256x256  ASCII 32..126
 *   HeadFont    0x3d9cb8  0x3da338     HeadFont    128x256  space, '-', A-Z-W
 *   SmallFont   0x3e23b8  0x3e3b18     SmallFont   128x128  ASCII 32..126
 *
 * All three atlases are WHITE glyphs + DXT5 alpha; colour is applied by the
 * 2D pipeline's vertex colours at draw time.
 *
 * INPUT: the ELF is $B3_ELF if set, else "build/burnout3.elf" relative to the
 * process CWD -- exactly the path the python tool derives from the repo root.
 */
#include "cx_art_common.h"
#include "cx_extract.h"
#include "cx_png.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    const char *name;
    uint32_t    obj;
    uint32_t    rec;
    uint32_t    slot;
} FontDef;

/* (name, object VA, texture record VA, pointer slot) -- see the file comment */
static const FontDef FONTS[3] = {
    { "GlobalFont", 0x3C84D8u, 0x3C9C38u, 0x3E7B98u },
    { "HeadFont",   0x3D9CB8u, 0x3DA338u, 0x3E7BB0u },
    { "SmallFont",  0x3E23B8u, 0x3E3B18u, 0x3E7BA4u },
};

typedef struct {
    int   present;
    float u, v, gw, gh, xo, yo, adv;
} Glyph;

typedef struct {
    char  name[32];
    int   w, h;
    Glyph glyph[95];        /* 0x20..0x7E */
} FontMeta;

static float f32_of(const unsigned char *p)
{
    uint32_t v = (uint32_t)p[0] | ((uint32_t)p[1] << 8)
               | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
    float f;
    memcpy(&f, &v, 4);
    return f;
}

static uint32_t u32_of(const unsigned char *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16)
         | ((uint32_t)p[3] << 24);
}

/* extract_font.py's emit_header(), line for line. */
static int emit_header(const char *path, const FontMeta *fonts, int nfonts)
{
    FILE *f;
    int i, c;

    f = fopen(path, "w");
    if (!f)
        return -1;
    fprintf(f, "%s\n", "/* GENERATED by tools/extract_font.py -- do not edit.");
    fprintf(f, "%s\n", " *");
    fprintf(f, "%s\n", " * Burnout 3's three fonts, recovered from the XBE .data section");
    fprintf(f, "%s\n", " * (font objects 0x3c84d8/0x3d9cb8/0x3e23b8 + embedded DXT5 texture");
    fprintf(f, "%s\n", " * records 0x3c9c38/0x3da338/0x3e3b18; glyph record layout proven by");
    fprintf(f, "%s\n", " * FUN_001c1060's charmap walk -- see tools/extract_font.py and");
    fprintf(f, "%s\n", " * docs/RE_FRONTEND.md section 6).  Pixel-space metrics; the atlases");
    fprintf(f, "%s\n", " * (build/frontend/<name>.png) are white + alpha, colour is applied");
    fprintf(f, "%s\n", " * at draw time exactly as the game's 2D pipeline does.");
    fprintf(f, "%s\n", " */");
    fprintf(f, "%s\n", "#ifndef BURNOUT3_FONT_H");
    fprintf(f, "%s\n", "#define BURNOUT3_FONT_H");
    fprintf(f, "%s\n", "");
    fprintf(f, "%s\n", "typedef struct B3Glyph {");
    fprintf(f, "%s\n", "    float u0, v0, u1, v1;   /* normalized atlas rect */");
    fprintf(f, "%s\n", "    float w, h;             /* glyph size, atlas px  */");
    fprintf(f, "%s\n", "    float xoff, yoff;       /* pen offset, atlas px  */");
    fprintf(f, "%s\n", "    float advance;          /* pen advance, atlas px */");
    fprintf(f, "%s\n", "    unsigned char present;  /* 0 = font has no glyph */");
    fprintf(f, "%s\n", "} B3Glyph;");
    fprintf(f, "%s\n", "");
    fprintf(f, "%s\n", "typedef struct B3Font {");
    fprintf(f, "%s\n", "    const char *name;       /* atlas basename in build/frontend */");
    fprintf(f, "%s\n", "    int tex_w, tex_h;");
    fprintf(f, "%s\n", "    float line_h;           /* max glyph yoff+h, atlas px */");
    fprintf(f, "%s\n", "    B3Glyph glyph[95];      /* chars 0x20..0x7E */");
    fprintf(f, "%s\n", "} B3Font;");
    fprintf(f, "%s\n", "");

    for (i = 0; i < nfonts; i++) {
        const FontMeta *fm = &fonts[i];
        double line_h = 0.0;
        int first = 1;
        char lname[32];
        size_t k;

        /* max(g.yoff * h + g.h * h) over the MAPPED glyphs only */
        for (c = 0; c < 95; c++) {
            double v;
            if (!fm->glyph[c].present)
                continue;
            v = (double)fm->glyph[c].yo * (double)fm->h
              + (double)fm->glyph[c].gh * (double)fm->h;
            if (first || v > line_h) { line_h = v; first = 0; }
        }
        for (k = 0; k < sizeof lname - 1 && fm->name[k]; k++) {
            char ch = fm->name[k];
            lname[k] = (ch >= 'A' && ch <= 'Z') ? (char)(ch - 'A' + 'a') : ch;
        }
        lname[k] = 0;

        fprintf(f, "static const B3Font b3_font_%s = {\n", lname);
        fprintf(f, "    \"%s\", %d, %d, %.3ff,\n", fm->name, fm->w, fm->h,
                line_h);
        fprintf(f, "%s\n", "    {");
        for (c = 0; c < 95; c++) {
            const Glyph *g = &fm->glyph[c];
            int ch = 0x20 + c;
            char cs[4];

            /* cs = chr(c) if chr(c) not in "\\'" else "\\" + chr(c) */
            if (ch == '\\' || ch == '\'') {
                cs[0] = '\\'; cs[1] = (char)ch; cs[2] = 0;
            } else {
                cs[0] = (char)ch; cs[1] = 0;
            }
            if (!g->present) {
                fprintf(f, "    {0,0,0,0, 0,0, 0,0, 0, 0}, /* '%s' absent */\n",
                        cs);
                continue;
            }
            fprintf(f, "    {%.6ff,%.6ff,%.6ff,%.6ff, %.1ff,%.1ff, %.1ff,%.1ff,"
                       " %.1ff, 1}, /* '%s' */\n",
                    (double)g->u, (double)g->v,
                    (double)g->u + (double)g->gw,
                    (double)g->v + (double)g->gh,
                    (double)g->gw * fm->w, (double)g->gh * fm->h,
                    (double)g->xo * fm->w, (double)g->yo * fm->h,
                    (double)g->adv * fm->w, cs);
        }
        fprintf(f, "%s\n", "    }");
        fprintf(f, "%s\n", "};");
        fprintf(f, "%s\n", "");
    }
    fprintf(f, "%s\n", "#endif /* BURNOUT3_FONT_H */");
    if (fclose(f) != 0)
        return -1;
    return 0;
}

/* ----------------------------------------------- the RUNTIME asset, font.bin
 *
 * The same three glyph tables emit_header() writes, as a file the port loads
 * at boot instead of compiling in (cx_extract.h, "purge 2"; the loader is
 * src/burnout3_font_runtime.h).  Format spec in that block.
 *
 * Every number goes through qf(), which formats it with THE HEADER'S OWN
 * format and parses it back.  That is not decoration: emit_header() prints the
 * UVs "%.6f" and the pixel metrics "%.1f", so the compiled constants are the
 * ROUNDED decimals, and the port's [S-ref] HUD offsets were measured against
 * them.  Rounding here is what makes the loaded table bit-identical to the
 * compiled one instead of merely close to it. */
static float qf(double v, const char *fmt)
{
    char buf[64];
    snprintf(buf, sizeof buf, fmt, v);
    return (float)strtod(buf, NULL);
}

static void bin_u32(FILE *f, uint32_t v)
{
    unsigned char b[4];
    b[0] = (unsigned char)(v & 0xFFu);
    b[1] = (unsigned char)((v >> 8) & 0xFFu);
    b[2] = (unsigned char)((v >> 16) & 0xFFu);
    b[3] = (unsigned char)((v >> 24) & 0xFFu);
    fwrite(b, 1, 4, f);
}

static void bin_f32q(FILE *f, double v, const char *fmt)
{
    float x = qf(v, fmt);
    uint32_t u;
    memcpy(&u, &x, 4);
    bin_u32(f, u);
}

static int emit_font_bin(const char *path, const FontMeta *fonts, int nfonts)
{
    FILE *f;
    int i, c;

    f = fopen(path, "wb");
    if (!f)
        return -1;
    fwrite("B3FN", 1, 4, f);
    bin_u32(f, 1);
    bin_u32(f, (uint32_t)nfonts);
    bin_u32(f, 95);
    for (i = 0; i < nfonts; i++) {
        const FontMeta *fm = &fonts[i];
        double line_h = 0.0;
        int first = 1;
        char name[32];

        /* emit_header()'s own line_h: max(yoff + h) over the MAPPED glyphs */
        for (c = 0; c < 95; c++) {
            double v;
            if (!fm->glyph[c].present)
                continue;
            v = (double)fm->glyph[c].yo * (double)fm->h
              + (double)fm->glyph[c].gh * (double)fm->h;
            if (first || v > line_h) { line_h = v; first = 0; }
        }
        memset(name, 0, sizeof name);
        strncpy(name, fm->name, sizeof name - 1);
        fwrite(name, 1, sizeof name, f);
        bin_u32(f, (uint32_t)fm->w);
        bin_u32(f, (uint32_t)fm->h);
        bin_f32q(f, line_h, "%.3f");
        for (c = 0; c < 95; c++) {
            const Glyph *g = &fm->glyph[c];
            unsigned char tail[4] = { 0, 0, 0, 0 };
            if (!g->present) {
                /* the header's absent row is all-zero, present = 0 */
                int k;
                for (k = 0; k < 9; k++)
                    bin_u32(f, 0);
                fwrite(tail, 1, 4, f);
                continue;
            }
            bin_f32q(f, (double)g->u, "%.6f");
            bin_f32q(f, (double)g->v, "%.6f");
            bin_f32q(f, (double)g->u + (double)g->gw, "%.6f");
            bin_f32q(f, (double)g->v + (double)g->gh, "%.6f");
            bin_f32q(f, (double)g->gw * fm->w, "%.1f");
            bin_f32q(f, (double)g->gh * fm->h, "%.1f");
            bin_f32q(f, (double)g->xo * fm->w, "%.1f");
            bin_f32q(f, (double)g->yo * fm->h, "%.1f");
            bin_f32q(f, (double)g->adv * fm->w, "%.1f");
            tail[0] = 1;
            fwrite(tail, 1, 4, f);
        }
    }
    if (fclose(f) != 0)
        return -1;
    return 0;
}

int cx_extract_font(const char *game_dir, const char *out_root)
{
    const char *elf_path;
    cxe_elf img;
    FontMeta meta[3];
    char outdir[4096], srcdir[4096], path[4352];
    unsigned char *rgba = NULL;
    unsigned char buf[512];
    int i, rc = 1;

    (void)game_dir;                    /* the fonts live in the executable */

    elf_path = getenv("B3_ELF");
    if (!elf_path || !elf_path[0])
        elf_path = "build/burnout3.elf";
    if (!cxb_file_exists(elf_path)) {
        fprintf(stderr, "[cx_art_font] missing %s -- run tools/xbe2elf.py "
                        "first (or set B3_ELF)\n", elf_path);
        return 1;
    }
    if (cxe_elf_open(elf_path, &img) != 0) {
        fprintf(stderr, "[cx_art_font] %s: not an ELF\n", elf_path);
        return 1;
    }
    if (cxe_out_dir(outdir, sizeof outdir, out_root, "build/frontend") != 0
        || cxe_out_dir(srcdir, sizeof srcdir, out_root, "src") != 0) {
        fprintf(stderr, "[cx_art_font] cannot create the output tree under "
                        "%s\n", out_root);
        goto done;
    }

    for (i = 0; i < 3; i++) {
        const FontDef *fd = &FONTS[i];
        uint32_t slot, fmt, w, h, bmp_off, default_off;
        uint32_t offs[128];
        char recname[20];
        int ok = 0, c, nmapped = 0;
        size_t need;

        /* --- structural verification --------------------------------- */
        slot = cxe_elf_u32(&img, fd->slot, &ok);
        if (!ok || slot != fd->obj) {
            fprintf(stderr, "[cx_art_font] %s: pointer slot %#x -> %#x, "
                            "expected %#x\n", fd->name, fd->slot, slot,
                    fd->obj);
            goto done;
        }
        if (cxe_elf_read(&img, fd->obj, 4, buf) != 0
            || memcmp(buf, "3rev", 4) != 0) {
            fprintf(stderr, "[cx_art_font] %s: bad object magic\n", fd->name);
            goto done;
        }
        if (cxe_elf_read(&img, fd->rec + 0x48u, 16, buf) != 0) {
            fprintf(stderr, "[cx_art_font] %s: texture record unmapped\n",
                    fd->name);
            goto done;
        }
        /* python: img.read(rec+0x48, 16).split(b"\0")[0].decode() */
        memcpy(recname, buf, 16);
        recname[16] = 0;
        if (strcmp(recname, fd->name) != 0) {
            fprintf(stderr, "[cx_art_font] %s: texture record name is '%s'\n",
                    fd->name, recname);
            goto done;
        }
        fmt     = cxe_elf_u32(&img, fd->rec + 0x34u, NULL);
        w       = cxe_elf_u32(&img, fd->rec + 0x38u, NULL);
        h       = cxe_elf_u32(&img, fd->rec + 0x3Cu, NULL);
        bmp_off = cxe_elf_u32(&img, fd->rec + 0x04u, NULL);
        if (fmt != CXB_FMT_DXT5 || bmp_off != 0x80u) {
            fprintf(stderr, "[cx_art_font] %s: unexpected fmt %#x / bmp off "
                            "%#x\n", fd->name, fmt, bmp_off);
            goto done;
        }
        if (!(w > 0u && w <= 4096u && h > 0u && h <= 4096u)) {
            fprintf(stderr, "[cx_art_font] %s: bad dims %ux%u\n", fd->name,
                    w, h);
            goto done;
        }

        /* --- bitmap (DXT5 = 1 byte/pixel) ---------------------------- */
        need = (size_t)w * (size_t)h;
        {
            unsigned char *dxt = (unsigned char *)malloc(need);
            cxb_blob src;
            if (!dxt)
                goto done;
            if (cxe_elf_read(&img, fd->rec + 0x80u, need, dxt) != 0) {
                free(dxt);
                fprintf(stderr, "[cx_art_font] %s: bitmap unmapped\n",
                        fd->name);
                goto done;
            }
            free(rgba);
            rgba = (unsigned char *)malloc(need * 4u);
            if (!rgba) { free(dxt); goto done; }
            src.d = dxt;
            src.n = need;
            if (cxb_decode_dxt(&src, 0, (int)w, (int)h, CXB_FMT_DXT5,
                               rgba) != 0) {
                free(dxt);
                fprintf(stderr, "[cx_art_font] %s: DXT5 decode failed\n",
                        fd->name);
                goto done;
            }
            free(dxt);
        }
        if ((size_t)snprintf(path, sizeof path, "%s/%s.png", outdir, fd->name)
            >= sizeof path)
            goto done;
        if (cx_png_write_rgba8(path, rgba, (int)w, (int)h) != 0) {
            fprintf(stderr, "[cx_art_font] cannot write %s\n", path);
            goto done;
        }

        /* --- glyph table --------------------------------------------- */
        snprintf(meta[i].name, sizeof meta[i].name, "%s", fd->name);
        meta[i].w = (int)w;
        meta[i].h = (int)h;
        memset(meta[i].glyph, 0, sizeof meta[i].glyph);

        default_off = cxe_elf_u32(&img, fd->obj + 0x1Cu, NULL);
        if (cxe_elf_read(&img, fd->obj + 0x20u, 512, buf) != 0)
            goto done;
        for (c = 0; c < 128; c++)
            offs[c] = u32_of(buf + c * 4);

        for (c = 0x20; c < 0x7F; c++) {
            /* FUN_001c1060's exact walk: charmap[c & 0x7F] is the FIRST
             * record whose (charcode & 0x7F) == c; on charcode mismatch step
             * 0x20-stride sibling records until the default record. */
            uint32_t o = offs[c];
            unsigned char gr[28];
            int guard = 0;
            float u, v, gw, gh, xo, yo, adv;
            Glyph *g;

            while (o != default_off) {
                unsigned char cc[4];
                if (cxe_elf_read(&img, fd->obj + o + 28u, 4, cc) != 0)
                    break;
                if (u32_of(cc) == (uint32_t)c)
                    break;
                o += 0x20u;
                if (++guard > 4096)             /* the python would spin */
                    break;
            }
            if (o == default_off || guard > 4096)
                continue;
            if (cxe_elf_read(&img, fd->obj + o, 28, gr) != 0)
                continue;
            u   = f32_of(gr);
            v   = f32_of(gr + 4);
            gw  = f32_of(gr + 8);
            gh  = f32_of(gr + 12);
            xo  = f32_of(gr + 16);
            yo  = f32_of(gr + 20);
            adv = f32_of(gr + 24);
            if (u < 0.0f || gh == 0.0f) {
                /* blank glyph (space uses u = v = -1): advance only */
                u = v = gw = gh = 0.0f;
            }
            if (!(u >= 0.0f && u <= 1.0f && v >= 0.0f && v <= 1.0f
                  && (double)u + gw >= 0.0 && (double)u + gw <= 1.001
                  && (double)v + gh >= 0.0 && (double)v + gh <= 1.001)) {
                fprintf(stderr, "[cx_art_font] %s: glyph '%c' bad UVs\n",
                        fd->name, c);
                goto done;
            }
            g = &meta[i].glyph[c - 0x20];
            g->present = 1;
            g->u = u; g->v = v; g->gw = gw; g->gh = gh;
            g->xo = xo; g->yo = yo; g->adv = adv;
            nmapped++;
        }
        if (!meta[i].glyph[0].present) {         /* ' ' */
            fprintf(stderr, "[cx_art_font] %s: no space glyph\n", fd->name);
            goto done;
        }
        if (strcmp(fd->name, "HeadFont") != 0) {
            int dch;
            for (dch = 0x30; dch < 0x3A; dch++) {
                if (!meta[i].glyph[dch - 0x20].present) {
                    fprintf(stderr, "[cx_art_font] %s: digit '%c' missing\n",
                            fd->name, dch);
                    goto done;
                }
            }
        }
        printf("%s: %dx%d DXT5, %d glyphs mapped\n", fd->name, (int)w, (int)h,
               nmapped);
    }

    if ((size_t)snprintf(path, sizeof path, "%s/burnout3_font.h", srcdir)
        >= sizeof path)
        goto done;
    if (emit_header(path, meta, 3) != 0) {
        fprintf(stderr, "[cx_art_font] cannot write %s\n", path);
        goto done;
    }
    printf("wrote %s\n", path);

    /* and the same metrics as the RUNTIME asset the port actually loads */
    if ((size_t)snprintf(path, sizeof path, "%s/font.bin", outdir)
        >= sizeof path)
        goto done;
    if (emit_font_bin(path, meta, 3) != 0) {
        fprintf(stderr, "[cx_art_font] cannot write %s\n", path);
        goto done;
    }
    printf("wrote %s\n", path);
    rc = 0;

done:
    free(rgba);
    cxe_elf_close(&img);
    return rc;
}
