/* cx_gen_crash_ranges.c -- the C port of tools/gen_crash_ranges.py.
 *
 * Emit the vehicle fields FUN_0011AEF0 reads and writes.
 *
 * The chassis-vs-world resolve's interface, as B3VehicleFull members so the
 * table is derived from the parity assertions and cannot drift.
 *
 * The list comes from B3CrashVehicle, the port's fourth partial view of the
 * vehicle object -- 26 fields, every one of them at a vehicle offset that
 * B3VehicleFull already models.  That view is built and written back on every
 * call by b3_vehicle_chassis_contact, so the RE path keeps it; the retail path
 * does not need it and works off B3VehicleFull directly.
 *
 * Two of those 26 are worth naming:
 *   * v+0x1404 appears as `ground_frac` there and `brake_1404` here.  One
 *     address, two names -- the bridge already writes `cv.ground_frac =
 *     v->brake_1404`.  validate_ai pins it: retail's driver puts the BRAKE
 *     there (brk = rf(VEH+0x1404)), so brake_1404 is the name that matches
 *     the game.
 *   * v+0x020E (`asleep`) existed ONLY in that view and is now on the vehicle.
 *
 * The python original refuses to emit a member with no parity assertion; so
 * does this, because a table row that is not backed by an assertion is exactly
 * the drift the generator exists to prevent.
 */
#include "cx_common_g.h"
#include "cx_extract.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* B3CrashVehicle field  ->  the B3VehicleFull member at the same offset.
 * Already in ascending offset order, and python's sort is stable, so the
 * emitted order is this order. */
static const struct {
    const char *member;
    unsigned    off;
} CXG_CRASH_IFACE[] = {
    { "rb.inv_inertia_world", 0x0040 }, { "rb.inv_frame", 0x0070 },
    { "rb.vel", 0x00B0 }, { "rb.dir", 0x00C0 }, { "rb.omega", 0x00D0 },
    { "rb.force_acc", 0x00F0 }, { "rb.imp_force", 0x0110 },
    { "rb.imp_torque", 0x0120 }, { "rb.deflection", 0x0130 },
    { "contact_pt_160", 0x0160 }, { "contact_n_170", 0x0170 },
    { "surface_190", 0x0190 }, { "impact_194", 0x0194 },
    { "contact_state_198", 0x0198 }, { "half_ext", 0x01D0 },
    { "center_off", 0x01E0 }, { "mass", 0x01F0 }, { "asleep_020E", 0x020E },
    { "flags_1353", 0x1353 }, { "surface_grip_13A8", 0x13A8 },
    { "brake_1404", 0x1404 }, { "drift_dir_1434", 0x1434 },
    { "trans.gear", 0x14C8 }, { "drift_state_1524", 0x1524 },
    { "authority_1534", 0x1534 }, { "no_scrub_153E", 0x153E },
};
#define CXG_CRASH_N \
    ((int)(sizeof(CXG_CRASH_IFACE) / sizeof(CXG_CRASH_IFACE[0])))

/* python's `member.split(".")[0]`. */
static void cxg_base_member(const char *m, char *out, size_t cap)
{
    const char *dot = strchr(m, '.');
    size_t      n = dot ? (size_t)(dot - m) : strlen(m);

    if (n >= cap)
        n = cap - 1;
    memcpy(out, m, n);
    out[n] = '\0';
}

static int cxg_crash_build(cxg_str *L, const char *repo)
{
    char  path[4096];
    char *src;
    int   i;

    cxg_join(path, sizeof(path), repo, "src/burnout3_vehicle_sim.h");
    src = cxg_read_text(path, NULL);
    if (!src)
        return 1;

    for (i = 0; i < CXG_CRASH_N; i++) {
        char base[96];

        cxg_base_member(CXG_CRASH_IFACE[i].member, base, sizeof(base));
        if (!cxg_has_assert_for(src, "B3VehicleFull", base)) {
            fprintf(stderr, "crash iface: %s has no parity assertion\n",
                    CXG_CRASH_IFACE[i].member);
            free(src);
            return 1;
        }
    }
    free(src);

    cxg_sline(L, "// GENERATED by tools/gen_crash_ranges.py -- do not edit by hand.");
    cxg_sline(L, "//");
    cxg_sline(L, "// The vehicle fields FUN_0011AEF0 (chassis-vs-world resolve) touches.");
    cxg_sline(L, "// Each range is written at the SAME offset on both sides; nothing is");
    cxg_sline(L, "// converted, and the rest of retail's vehicle stays as the emulator");
    cxg_sline(L, "// seeded it -- including the veh+0x200 soup the resolve reads.");
    cxg_sline(L, "#ifndef BURNOUT3_CRASH_RANGES_H");
    cxg_sline(L, "#define BURNOUT3_CRASH_RANGES_H");
    cxg_nl(L);
    cxg_sline(L, "#include <stddef.h>");
    cxg_sline(L, "#include \"burnout3_vehicle_sim.h\"");
    cxg_nl(L);
    cxg_sline(L, "typedef struct { unsigned off, len; } B3CrashRange;");
    cxg_nl(L);
    cxg_sline(L, "#define B3_CRASHVEH_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))");
    cxg_sline(L, "static const B3CrashRange B3_CRASHVEH_RANGES[] = {");
    for (i = 0; i < CXG_CRASH_N; i++)
        cxg_sline(L, "    { (unsigned)offsetof(B3VehicleFull, %s), "
                     "B3_CRASHVEH_LEN(%s) },  // +0x%04X",
                  CXG_CRASH_IFACE[i].member, CXG_CRASH_IFACE[i].member,
                  CXG_CRASH_IFACE[i].off);
    cxg_sline(L, "};");
    cxg_sline(L, "#define B3_CRASHVEH_RANGES_COUNT "
                 "(sizeof(B3_CRASHVEH_RANGES)/sizeof(B3_CRASHVEH_RANGES[0]))");
    cxg_nl(L);
    cxg_sputs(L, "#endif // BURNOUT3_CRASH_RANGES_H\n");
    return 0;
}

int cx_extract_gen_crash_ranges(const char *game_dir, const char *out_root)
{
    const char *repo = cxg_repo_root();
    cxg_str     L = { 0 };
    char        out[4096], rel[4096];
    int         rc;

    (void)game_dir;              /* source of truth is src/, not the game */
    cxg_gen_path(out, sizeof(out), out_root, "burnout3_crash_ranges.h");
    rc = cxg_crash_build(&L, repo);
    if (rc == 0)
        rc = cxg_str_write(&L, out);
    cxg_str_free(&L);
    if (rc == 0) {
        cxg_relpath(rel, sizeof(rel), out, repo);
        printf("  %s: %d range(s)\n", rel, CXG_CRASH_N);
    }
    return rc;
}
