/* cx_gen_ai_ranges.c -- the C port of tools/gen_ai_ranges.py.
 *
 * Emit the recovered byte ranges of the AI gather structs.
 *
 * Same principle as gen_vehicle_ranges: each range is written at the SAME
 * offset on both sides, nothing is converted, and everything not recovered is
 * left as the emulator seeded it.  Built from the parity assertions so the
 * table cannot drift from the structs.
 *
 * The two structs go to DIFFERENT objects, and that is the whole point:
 *
 *     B3AiCar    -> the racecar object   (RC + off)
 *     B3AiInputs -> the physics vehicle  (VEH + off)
 *
 * B3AiCar used to carry ten vehicle fields at their VEHICLE offsets, so this
 * table sent them to RC+0xBC, RC+0x1470 and so on -- the wrong object.  They
 * were duplicates of B3VehicleFull fields at identical offsets and have been
 * removed; B3AiCar now holds a pointer to the vehicle, exactly as retail does
 * at racecar+0x2440.  The pointer is harness-side and never appears here.
 *
 * NOTE the assertion scan asks for the 0x prefix here.  gen_vehicle_ranges.py
 * deliberately does NOT (`(?:0x)?`), because the rigid body is asserted as
 * `== 0`; the AI header spells every offset with the prefix, and the python
 * original's regex says so.  The two spellings are kept apart on purpose.
 */
#include "cx_common_g.h"
#include "cx_extract.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define CXG_AIR_MAX 512

/* The vehicle fields FUN_00105340 actually reads and writes -- NOT the whole
 * vehicle.  Handing it the full B3_VEHICLE_RANGES table instead is
 * over-transfer: we would overwrite state the emulator seeded coherently with
 * state that is only coherent inside the port.  Measured with the full table:
 * 65 driver calls/s at ~15 ms each, the car crawling, against 82 game-seconds
 * in 60 with this list.
 *
 * This IS the function's interface, and it is derived the same way everything
 * else here is -- offsetof/sizeof over the parity-asserted struct, so a field
 * that moves breaks the build rather than the transfer. */
static const char *const CXG_AIVEH[] = {
    /* --- read: where the car is going --- */
    "rb.vel",               /* v+0x00B0, [3] = speed (v+0x00BC) */
    "rb.dir",               /* v+0x00C0  "carAt" heading */
    "rb.omega",             /* v+0x00D0, [1] = yaw rate (v+0x00D4) */
    /* --- read: the driver's gates --- */
    "lsdm_limit_13AC",
    "trans.change_up_rpm",  /* v+0x1470 */
    "trans.omega",          /* v+0x149C rad/s */
    "lsdm_active_1550",
    /* --- read AND write --- */
    "trans.gear",           /* v+0x14C8 */
    "drift_state_1524",
    "authority_1534",
    "steer_1408",           /* also the slew limiter's memory, carried in */
    /* --- write: the inputs the driver produces --- */
    "input_bits_13FC",
    "throttle_1400",
    "brake_1404",
    "throttle_raw_1414",
    "stop_flag_1552",
    /* --- write: the driver's own timers --- */
    "prev_throttle_156C",
    "brake_hold_1570",
    "dither_1574",
    "stuck_arm_1578",
    "reverse_timer_157C",
};
#define CXG_AIVEH_N ((int)(sizeof(CXG_AIVEH) / sizeof(CXG_AIVEH[0])))

/* python's sorted(..., key=offset): ascending, and STABLE, so equal offsets
 * keep the order the assertions appear in the file. */
static void cxg_sort_stable(cxg_assert_hit *h, int n)
{
    int i, j;

    for (i = 1; i < n; i++) {
        cxg_assert_hit k = h[i];

        for (j = i - 1; j >= 0 && h[j].off > k.off; j--)
            h[j + 1] = h[j];
        h[j + 1] = k;
    }
}

static void cxg_base_member(const char *m, char *out, size_t cap)
{
    const char *dot = strchr(m, '.');
    size_t      n = dot ? (size_t)(dot - m) : strlen(m);

    if (n >= cap)
        n = cap - 1;
    memcpy(out, m, n);
    out[n] = '\0';
}

static int cxg_air_build(cxg_str *L, const char *repo, int *n_car, int *n_ai)
{
    static const struct {
        const char *st;
        const char *macro;
    } TABLES[2] = { { "B3AiCar", "B3_AICAR" }, { "B3AiState", "B3_AISTATE" } };

    char            path[4096];
    char           *ai = NULL, *vh = NULL;
    cxg_assert_hit *hit = NULL;
    int             t, i, rc = 1;

    cxg_join(path, sizeof(path), repo, "src/burnout3_ai.h");
    ai = cxg_read_text(path, NULL);
    if (!ai)
        goto done;
    cxg_join(path, sizeof(path), repo, "src/burnout3_vehicle_sim.h");
    vh = cxg_read_text(path, NULL);
    if (!vh)
        goto done;
    hit = (cxg_assert_hit *)malloc(sizeof(*hit) * CXG_AIR_MAX);
    if (!hit)
        goto done;

    cxg_sline(L, "// GENERATED by tools/gen_ai_ranges.py -- do not edit by hand.");
    cxg_sline(L, "//");
    cxg_sline(L, "// Recovered byte ranges of the AI gather structs, at retail's offsets:");
    cxg_sline(L, "//   B3AiCar   -> the racecar object            (RC + off)");
    cxg_sline(L, "//   B3AiState -> the AI object EMBEDDED in it   (RC + 0x1A00 + off)");
    cxg_sline(L, "//");
    cxg_sline(L, "// The navigator ctor FUN_001705F0 writes the aggregate back-pointers at");
    cxg_sline(L, "// racecar+0x1A04/0x21A0/0x2160, which is what places the AI object at");
    cxg_sline(L, "// racecar+0x1A00. Its offsets are AI-relative, so the bias is applied at");
    cxg_sline(L, "// the transfer, not baked into the struct.");
    cxg_sline(L, "// The vehicle side needs no table here: the driver writes the physics");
    cxg_sline(L, "// vehicle directly, so B3_VEHICLE_RANGES carries it.");
    cxg_sline(L, "// Built from the parity assertions so they cannot drift from the structs.");
    cxg_sline(L, "#ifndef BURNOUT3_AI_RANGES_H");
    cxg_sline(L, "#define BURNOUT3_AI_RANGES_H");
    cxg_nl(L);
    cxg_sline(L, "#include <stddef.h>");
    cxg_sline(L, "#include \"burnout3_ai.h\"");
    cxg_sline(L, "#include \"burnout3_vehicle_sim.h\"");
    cxg_nl(L);
    cxg_sputs(L, "typedef struct { unsigned off, len; } B3AiRange;");

    for (t = 0; t < 2; t++) {
        int n = cxg_scan_assert(ai, TABLES[t].st, 1, hit, CXG_AIR_MAX);

        cxg_sort_stable(hit, n);
        cxg_nl(L);
        cxg_nl(L);
        cxg_sline(L, "#define %s_LEN(f) ((unsigned)sizeof(((%s*)0)->f))",
                  TABLES[t].macro, TABLES[t].st);
        cxg_sline(L, "static const B3AiRange %s_RANGES[] = {", TABLES[t].macro);
        for (i = 0; i < n; i++)
            cxg_sline(L, "    { (unsigned)offsetof(%s, %s), %s_LEN(%s) },",
                      TABLES[t].st, hit[i].name, TABLES[t].macro, hit[i].name);
        cxg_sline(L, "};");
        cxg_sprintf(L, "#define %s_RANGES_COUNT (sizeof(%s_RANGES)/sizeof(%s_RANGES[0]))",
                    TABLES[t].macro, TABLES[t].macro, TABLES[t].macro);
        if (t == 0)
            *n_car = n;
        else
            *n_ai = n;
    }

    for (i = 0; i < CXG_AIVEH_N; i++) {
        char base[96];

        cxg_base_member(CXG_AIVEH[i], base, sizeof(base));
        if (!cxg_has_assert_for(vh, "B3VehicleFull", base)) {
            fprintf(stderr, "AIVEH: %s has no parity assertion\n", CXG_AIVEH[i]);
            goto done;
        }
    }

    cxg_nl(L);
    cxg_nl(L);
    cxg_sline(L, "// The vehicle fields FUN_00105340 actually reads and writes.");
    cxg_sline(L, "#define B3_AIVEH_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))");
    cxg_sline(L, "static const B3AiRange B3_AIVEH_RANGES[] = {");
    for (i = 0; i < CXG_AIVEH_N; i++)
        cxg_sline(L, "    { (unsigned)offsetof(B3VehicleFull, %s), "
                     "B3_AIVEH_LEN(%s) },", CXG_AIVEH[i], CXG_AIVEH[i]);
    cxg_sline(L, "};");
    cxg_sline(L, "#define B3_AIVEH_RANGES_COUNT "
                 "(sizeof(B3_AIVEH_RANGES)/sizeof(B3_AIVEH_RANGES[0]))");

    /* The python original writes the file, then splices three lines in ahead
     * of the #endif and writes it again.  Only the second write survives, and
     * this is its content: two blank lines, the note, the offset. */
    cxg_nl(L);
    cxg_nl(L);
    cxg_sline(L, "// Retail embeds the AI object here; see FUN_001705F0.");
    cxg_sline(L, "#define B3_AI_OBJECT_OFFSET 0x1A00u");
    cxg_sputs(L, "#endif // BURNOUT3_AI_RANGES_H\n");
    rc = 0;

done:
    free(hit);
    free(ai);
    free(vh);
    return rc;
}

int cx_extract_gen_ai_ranges(const char *game_dir, const char *out_root)
{
    const char *repo = cxg_repo_root();
    cxg_str     L = { 0 };
    char        out[4096], rel[4096];
    int         n_car = 0, n_ai = 0, rc;

    (void)game_dir;
    cxg_gen_path(out, sizeof(out), out_root, "burnout3_ai_ranges.h");
    rc = cxg_air_build(&L, repo, &n_car, &n_ai);
    if (rc == 0)
        rc = cxg_str_write(&L, out);
    cxg_str_free(&L);
    if (rc == 0) {
        cxg_relpath(rel, sizeof(rel), out, repo);
        printf("  %s: %d car range(s), %d AI-object range(s)\n",
               rel, n_car, n_ai);
    }
    return rc;
}
