/* cx_gen_ai_pace.c -- the C port of tools/gen_ai_pace.py.
 *
 * Extract retail's per-opponent AI PACE RECORDS into burnout3_ai_pace.h.
 *
 * WHAT THIS IS
 * ------------
 * The rubber band in Burnout 3 is not a constant: how long each rival keeps
 * its catch-up licence is *event data*, one byte per grid slot, shipped inside
 * every Tracks/<REG>/<Cn_Vn>/Gamedata.bgd.
 *
 * The consumer is FUN_00172870 (`burnout3.elf`, .text = flat + 0x10000), the
 * AI navigator's pace-record reader, called once per car from the AI
 * constructor FUN_001718A0.  Its record branch is at 0x001728DD..0x00172A20:
 *
 *     slot = (s8) racecar+0x19BC                       # the GRID SLOT, 0..5
 *     if (DAT_0073A170 == 0 || slot >= DAT_0073A180)   # no record for it
 *         ... defaults, AI+0x9E8 = 0 ...               # @0x001728F0
 *     else:
 *         rec = DAT_0073A170 + slot * 0x98             # @0x00172937
 *         AI+0x9E4 = rec[0x97] * 0.01
 *         AI+0x9E8 = rec[0x93] * 0.01     <-- THE CATCH-UP WINDOW
 *         AI+0x9EC = rec[0x90] * 0.01     <-- aggression, also to AI+0x9E0
 *         AI+0x9F0 = rec[0x92] * 0.01
 *         AI+0x9F4 = rec[0x91] * 0.01
 *         AI+0x9F8 = (s8) rec[0x95]
 *         AI+0xA12 = (rec[0x96] & 1) == 1
 *
 * and the table base is installed by the .bgd loader FUN_0018B250:
 *
 *     @0x0018B478   DAT_0073A170 = <the 0x800-byte event PARAM record>
 *     @0x0018B48A   DAT_0073A180 = param[0x3B4]        # opponent count
 *
 * So a pace record is `param_record + grid_slot * 0x98`, six of them tiling
 * 0x000..0x390, immediately below the medal thresholds RE_BGD documents at
 * +0x3A0/+0x3A4/+0x3A8 and the opponent count at +0x3B4.  That tiling is the
 * cross-check: 0x10 + 16*4 + 16*4 + 8 == 0x98 exactly, and 6 * 0x98 == 0x390
 * lands exactly on the first documented field.  [C]
 *
 * Slot 0's first 0x10 bytes are the event's packed car ID (RE_BGD section 3);
 * FUN_00172870 never reads rec[0x00..0x0F], so the overlap is harmless -- and
 * slot 0 is the human player, who has no AI navigator at all.
 *
 * NOTE THE BASE-40.  This generator ships its own decoder, WITHOUT the
 * reversal tools/extract_tlist.py applies, which is why its event ids read
 * "FCRGSFFO" where the tlist decoder would read "OFFSGRCF".  That is the
 * python original's behaviour and the emitted table depends on it, so
 * cxg_b40_raw is deliberately the one used here.
 */
#define _POSIX_C_SOURCE 200809L

#include "cx_common_g.h"
#include "cx_extract.h"
#include "cx_src.h"   /* the dump may be a directory OR an ISO */

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#define CXG_PACE_STRIDE  0x98    /* @0x00172937  imul $0x98                */
#define CXG_PACE_SLOTS   6       /* the shipped race field size            */
#define CXG_PACE_OFF     0x90    /* the byte block FUN_00172870 reads      */
#define CXG_PACE_NOPP    0x3B4   /* @0x0018B484  DAT_0073A180              */
#define CXG_PACE_IDS     0x08    /* 18 packed event IDs                    */
#define CXG_PACE_RECS    0x198   /* 18 u32 offsets of the 0x800 params     */
#define CXG_PACE_NEVENT  18

static const char CXG_PACE_HEADER[] =
    "// GENERATED by tools/gen_ai_pace.py -- do not edit by hand.\n"
    "//\n"
    "// Retail's per-opponent AI pace records, read out of the shipped\n"
    "// Tracks/<REG>/<Cn_Vn>/Gamedata.bgd event param blocks at\n"
    "// `param + grid_slot * 0x98 + 0x90`.  The consumer is FUN_00172870\n"
    "// @0x001728DD (see the generator's docstring for the full decode); every\n"
    "// byte below is file data, none of it is tuned here.  [C]\n"
    "//\n"
    "//   aggression  rec+0x90 * 0.01 -> AI+0x9EC and AI+0x9E0\n"
    "//   f91         rec+0x91 * 0.01 -> AI+0x9F4\n"
    "//   f92         rec+0x92 * 0.01 -> AI+0x9F0\n"
    "//   catchup     rec+0x93 * 0.01 -> AI+0x9E8, the fraction of the race for\n"
    "//                                  which FUN_001734C0's catch-up stays armed\n"
    "//   mode        (s8) rec+0x95   -> AI+0x9F8\n"
    "//   flags       rec+0x96 & 1    -> AI+0xA12\n"
    "//   f97         rec+0x97 * 0.01 -> AI+0x9E4\n"
    "//\n"
    "// rec+0x94 is not read by any retail code path and is carried verbatim.\n"
    "\n"
    "#ifndef BURNOUT3_AI_PACE_H\n"
    "#define BURNOUT3_AI_PACE_H\n"
    "\n"
    "#define B3_AI_PACE_SLOTS 6\n"
    "\n"
    "typedef struct B3AiPaceRec {\n"
    "    unsigned char aggression, f91, f92, catchup, raw94, mode, flags, f97;\n"
    "} B3AiPaceRec;\n"
    "\n"
    "typedef struct B3AiPaceEvent {\n"
    "    const char*  track;      /* \"US_C3_V1\"                        */\n"
    "    const char*  event;      /* \"FCRGSFFO\" -- the mode-name table  */\n"
    "    unsigned char n_opp;     /* param+0x3B4                        */\n"
    "    B3AiPaceRec  slot[B3_AI_PACE_SLOTS];\n"
    "} B3AiPaceEvent;\n"
    "\n"
    "/* The offline forward single race -- the port's default event.\n"
    " * .data 0x3E9CD8's mode-name table: Off + SgRc + F. */\n"
    "#define B3_AI_PACE_DEFAULT_EVENT \"FCRGSFFO\"\n"
    "\n";

static const char CXG_PACE_FOOTER[] =
    "\n"
    "static const int B3_AI_PACE_COUNT =\n"
    "    (int)(sizeof(B3_AI_PACE) / sizeof(B3_AI_PACE[0]));\n"
    "\n"
    "/* FUN_00172870's lookup, minus the DAT_0073A170 indirection: the loader has\n"
    " * already chosen an event, so the port names it.  Returns NULL when the track\n"
    " * or event is unknown, which is retail's no-record branch (@0x001728F0):\n"
    " * AI+0x9E8 = 0, i.e. catch-up expires on the first frame. */\n"
    "static inline const B3AiPaceEvent*\n"
    "b3_ai_pace_find(const char* track, const char* event)\n"
    "{\n"
    "    int i;\n"
    "    const char* a;\n"
    "    const char* b;\n"
    "    if (!track) return 0;\n"
    "    if (!event || !*event) event = B3_AI_PACE_DEFAULT_EVENT;\n"
    "    for (i = 0; i < B3_AI_PACE_COUNT; i++) {\n"
    "        for (a = B3_AI_PACE[i].track, b = track; *a && *a == *b; a++, b++) { }\n"
    "        if (*a || *b) continue;\n"
    "        for (a = B3_AI_PACE[i].event, b = event; *a && *a == *b; a++, b++) { }\n"
    "        if (*a || *b) continue;\n"
    "        return &B3_AI_PACE[i];\n"
    "    }\n"
    "    return 0;\n"
    "}\n"
    "\n"
    "/* AI+0x9E8 for one grid slot.  Retail's own gate is `slot >= DAT_0073A180`\n"
    " * (@0x001728DD), the opponent count, so a slot past the field gets 0. */\n"
    "static inline float b3_ai_pace_catchup_window(const B3AiPaceEvent* ev, int slot)\n"
    "{\n"
    "    if (!ev || slot < 0 || slot >= B3_AI_PACE_SLOTS) return 0.0f;\n"
    "    if (slot >= (int)ev->n_opp) return 0.0f;\n"
    "    return (float)ev->slot[slot].catchup * 0.01f;\n"
    "}\n"
    "\n"
    "/* AI+0x9EC / AI+0x9E0, the per-opponent aggression the attack machine gates on\n"
    " * (\"Min. aggression before we start attacking\" = 0.002). */\n"
    "static inline float b3_ai_pace_aggression(const B3AiPaceEvent* ev, int slot)\n"
    "{\n"
    "    if (!ev || slot < 0 || slot >= B3_AI_PACE_SLOTS) return 0.0f;\n"
    "    if (slot >= (int)ev->n_opp) return 0.0f;\n"
    "    return (float)ev->slot[slot].aggression * 0.01f;\n"
    "}\n"
    "\n"
    "#endif /* BURNOUT3_AI_PACE_H */\n";

/* ---------------------------------------------------------------- the walk */
typedef struct {
    char (*p)[4096];
    size_t n, cap;
} cxg_paths;

static void cxg_paths_add(cxg_paths *v, const char *s)
{
    if (v->n == v->cap) {
        size_t cap = v->cap ? v->cap * 2 : 64;
        void  *p = realloc(v->p, cap * sizeof(*v->p));

        if (!p)
            return;
        v->p = (char (*)[4096])p;
        v->cap = cap;
    }
    snprintf(v->p[v->n], sizeof(v->p[0]), "%s", s);
    v->n++;
}

static int cxg_paths_cmp(const void *a, const void *b)
{
    return strcmp((const char *)a, (const char *)b);
}

/* The directory test the glob below needs now rides on CxSrcList.is_dir, so
 * only the file test is left standing. */
static int cxg_is_file(const char *p)
{
    return cx_vfs_is_file(p);
}

/* python's sorted(glob(...)) over Tracks/<any>/<any>/Gamedata.bgd.  glob's
 * `*` never matches a leading dot, and the sort is over the whole path
 * string, not the directory names. */
static void cxg_pace_find(const char *root, cxg_paths *v)
{
    char       tracks[4096], reg[4096], var[4096], bgd[4096];
    CxSrcList  l1, l2;
    int        i, j;

    cxg_join(tracks, sizeof(tracks), root, "Tracks");
    if (cx_vfs_listdir(tracks, &l1) != 0)
        return;
    for (i = 0; i < l1.n; i++) {
        if (l1.name[i][0] == '.')
            continue;
        cxg_join(reg, sizeof(reg), tracks, l1.name[i]);
        if (!l1.is_dir[i])
            continue;
        if (cx_vfs_listdir(reg, &l2) != 0)
            continue;
        for (j = 0; j < l2.n; j++) {
            if (l2.name[j][0] == '.')
                continue;
            cxg_join(var, sizeof(var), reg, l2.name[j]);
            if (!l2.is_dir[j])
                continue;
            cxg_join(bgd, sizeof(bgd), var, "Gamedata.bgd");
            if (cxg_is_file(bgd))
                cxg_paths_add(v, bgd);
        }
        cx_src_list_free(&l2);
    }
    cx_src_list_free(&l1);
    qsort(v->p, v->n, sizeof(*v->p), cxg_paths_cmp);
}

/* python's `path.replace('\\','/').split('/')[-3:-1]` joined with '_'. */
static void cxg_pace_track_id(const char *path, char *out, size_t cap)
{
    const char *seg[8];
    int         n = 0;
    const char *p = path;

    while (*p) {
        const char *e;

        while (*p == '/' || *p == '\\')
            p++;
        if (!*p)
            break;
        seg[n % 8] = p;
        n++;
        for (e = p; *e && *e != '/' && *e != '\\'; e++) { }
        p = e;
    }
    if (n < 3) {
        snprintf(out, cap, "?");
        return;
    }
    {
        const char *a = seg[(n - 3) % 8];
        const char *b = seg[(n - 2) % 8];
        size_t      la = strcspn(a, "/\\");
        size_t      lb = strcspn(b, "/\\");

        snprintf(out, cap, "%.*s_%.*s", (int)la, a, (int)lb, b);
    }
}

typedef struct {
    char          track[64];
    char          event[16];
    unsigned      n_opp;
    unsigned char slot[CXG_PACE_SLOTS][8];
} cxg_pace_row;

static int cxg_pace_build(cxg_str *L, const char *root, size_t *n_rows,
                          size_t *n_tracks, int *have_std, int *lo, int *hi)
{
    cxg_paths     files = { NULL, 0, 0 };
    cxg_pace_row *rows = NULL;
    size_t        nr = 0, cap = 0, i;
    char          seen[64][64];
    size_t        nseen = 0;
    int           rc = 1;

    cxg_pace_find(root, &files);
    if (!files.n) {
        fprintf(stderr, "no Gamedata.bgd under %s/Tracks\n", root);
        goto done;
    }

    for (i = 0; i < files.n; i++) {
        cxg_blob b;
        char     track[64];
        int      e;

        if (cxg_blob_load(&b, files.p[i]) != 0)
            goto done;
        if (b.n < 0x4000 || cxg_u32(&b, 4) != 0x320178) {
            printf("  skip (bad header): %s\n", files.p[i]);
            cxg_blob_free(&b);
            continue;
        }
        cxg_pace_track_id(files.p[i], track, sizeof(track));

        for (e = 0; e < CXG_PACE_NEVENT; e++) {
            uint64_t idv = cxg_u64(&b, CXG_PACE_IDS + (int64_t)e * 8);
            uint32_t ro  = cxg_u32(&b, CXG_PACE_RECS + (int64_t)e * 4);
            uint32_t n_opp;
            int      k;

            /* unused slots keep stale tool memory in both tables (RE_BGD) */
            if (!(ro >= 0x3000 && ro <= 0xB800 && ro % 0x800 == 0))
                continue;
            if ((uint64_t)ro + 0x800 > b.n)
                continue;
            n_opp = cxg_u32(&b, (int64_t)ro + CXG_PACE_NOPP);
            if (n_opp == 0 || n_opp > CXG_PACE_SLOTS)
                continue;
            if (nr == cap) {
                size_t nc = cap ? cap * 2 : 256;
                void  *p = realloc(rows, nc * sizeof(*rows));

                if (!p) {
                    cxg_blob_free(&b);
                    goto done;
                }
                rows = (cxg_pace_row *)p;
                cap = nc;
            }
            snprintf(rows[nr].track, sizeof(rows[nr].track), "%s", track);
            cxg_b40_raw(idv, rows[nr].event);
            rows[nr].n_opp = n_opp;
            for (k = 0; k < CXG_PACE_SLOTS; k++) {
                int64_t o = (int64_t)ro + (int64_t)k * CXG_PACE_STRIDE +
                            CXG_PACE_OFF;
                int     j;

                for (j = 0; j < 8; j++)
                    rows[nr].slot[k][j] = cxg_u8(&b, o + j);
            }
            nr++;
        }
        cxg_blob_free(&b);
    }

    cxg_sputs(L, CXG_PACE_HEADER);
    cxg_sline(L, "static const B3AiPaceEvent B3_AI_PACE[] = {");
    for (i = 0; i < nr; i++) {
        int k;

        cxg_sline(L, "    { \"%s\", \"%s\", %u, {", rows[i].track,
                  rows[i].event, rows[i].n_opp);
        for (k = 0; k < CXG_PACE_SLOTS; k++) {
            const unsigned char *s = rows[i].slot[k];

            cxg_sline(L, "        { %3d,%3d,%3d,%3d,%3d,%3d,%3d,%3d },"
                         "  /* slot %d  catch-up %.2f */",
                      s[0], s[1], s[2], s[3], s[4], s[5], s[6], s[7],
                      k, s[3] / 100.0);
        }
        cxg_sline(L, "    } },");
    }
    cxg_sputs(L, "};");
    cxg_nl(L);
    cxg_sputs(L, CXG_PACE_FOOTER);

    for (i = 0; i < nr; i++) {
        size_t j;

        for (j = 0; j < nseen; j++)
            if (!strcmp(seen[j], rows[i].track))
                break;
        if (j == nseen && nseen < sizeof(seen) / sizeof(seen[0]))
            snprintf(seen[nseen++], sizeof(seen[0]), "%s", rows[i].track);
    }
    *n_rows = nr;
    *n_tracks = nseen;

    *have_std = 0;
    for (i = 0; i < nr; i++) {
        int v;

        if (strcmp(rows[i].event, "FCRGSFFO") != 0)
            continue;
        v = rows[i].slot[5][3];
        if (!*have_std) {
            *lo = *hi = v;
            *have_std = 1;
        } else {
            if (v < *lo)
                *lo = v;
            if (v > *hi)
                *hi = v;
        }
    }
    rc = 0;

done:
    free(rows);
    free(files.p);
    return rc;
}

int cx_extract_gen_ai_pace(const char *game_dir, const char *out_root)
{
    cxg_str L = { 0 };
    char    out[4096];
    size_t  nr = 0, nt = 0;
    int     have_std = 0, lo = 0, hi = 0, rc;

    cxg_gen_path(out, sizeof(out), out_root, "burnout3_ai_pace.h");
    rc = cxg_pace_build(&L, game_dir, &nr, &nt, &have_std, &lo, &hi);
    if (rc == 0)
        rc = cxg_str_write(&L, out);
    cxg_str_free(&L);
    if (rc == 0) {
        printf("wrote %s: %zu events over %zu tracks\n", out, nr, nt);
        if (have_std)
            printf("  FCRGSFFO last-place catch-up window: %.2f .. %.2f "
                   "of the race\n", lo / 100.0, hi / 100.0);
    }
    return rc;
}
