#!/usr/bin/env python3
"""Emit a RETAIL-SHAPED vehicle struct from the port's own offset annotations.

Goal: one struct whose every field sits exactly where the game puts it, so the
port's C and the retail x86 can run over the SAME bytes with nothing marshalled
between them. Today the port is repacked -- 0 of 56 annotated fields land on
retail's offset -- which is what forces every interop hack.

Source of truth is the annotations already in src/burnout3_vehicle_sim.h
(`float mass;  // +0x1F0`) plus the offset #defines in
src/burnout3_vehicle_struct.h. This reads them, sorts by offset, reports every
conflict, and writes a struct with explicit padding and a _Static_assert per
field so the layout cannot drift silently.

    python3 tools/gen_retail_struct.py [-o src/burnout3_vehicle_retail.h]
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Retail's live vehicle object: the highest annotated offset is +0x1920
# (racecar class), and FUN_00110280 strides the traffic pool well past it.
SPAN = 0x1A00

SIZES = {
    "float": 4, "int": 4, "unsigned": 4, "unsigned int": 4,
    "unsigned short": 2, "short": 2,
    "unsigned char": 1, "signed char": 1, "char": 1,
}

FIELD = re.compile(
    r'^\s*(?P<type>(?:const\s+)?(?:unsigned\s+|signed\s+)?[A-Za-z_]\w*)\s+'
    r'(?P<name>\w+)\s*(?P<arr>(?:\[[^\]]*\])*)\s*;\s*(?://\s*(?P<c>.*))?$')
OFF_C = re.compile(r'\+0x([0-9A-Fa-f]{2,4})')
OFF_N = re.compile(r'_([0-9A-Fa-f]{3,4})$')
ARR = re.compile(r'\[(\d+)\]')


def sizeof(ctype, arr):
    base = SIZES.get(ctype.replace("const ", "").strip())
    if base is None:
        return None
    n = 1
    for d in ARR.findall(arr or ""):
        n *= int(d)
    return base * n


def collect(path, want):
    """(offset, name, ctype, arr, size) for annotated fields of `want`."""
    out, cur = [], None
    for line in open(path, errors="replace"):
        m = re.match(r'^\s*typedef struct (\w+)\s*\{', line)
        if m:
            cur = m.group(1)
            continue
        if cur and re.match(r'^\}\s*\w*\s*;', line):
            cur = None
            continue
        if cur != want:
            continue
        f = FIELD.match(line.rstrip())
        if not f:
            continue
        name, ctype, arr = f.group("name"), f.group("type"), f.group("arr")
        comment = f.group("c") or ""
        off = None
        c = OFF_C.search(comment)
        if c:
            off = int(c.group(1), 16)
        else:
            n = OFF_N.search(name)
            if n:
                off = int(n.group(1), 16)
        if off is None:
            continue
        sz = sizeof(ctype, arr)
        if sz is None:
            continue
        out.append((off, name, ctype, arr, sz))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--out",
                    default=os.path.join(ROOT, "src",
                                         "burnout3_vehicle_retail.h"))
    a = ap.parse_args()

    hdr = os.path.join(ROOT, "src", "burnout3_vehicle_sim.h")
    fields = collect(hdr, "B3VehicleFull")
    fields.sort(key=lambda r: (r[0], r[1]))

    # --- conflicts: two fields claiming overlapping bytes -----------------
    kept, dropped = [], []
    end = 0
    for off, name, ctype, arr, sz in fields:
        if off < end:
            dropped.append((off, name, sz, end))
            continue
        if off + sz > SPAN:
            dropped.append((off, name, sz, -1))
            continue
        kept.append((off, name, ctype, arr, sz))
        end = off + sz

    L = []
    L.append("// GENERATED by tools/gen_retail_struct.py -- do not edit by hand.")
    L.append("//")
    L.append("// Burnout 3's live vehicle object, at RETAIL's own offsets.")
    L.append("//")
    L.append("// The point of this shape is that there is nothing to convert: the")
    L.append("// port's C and the game's x86 address the same bytes at the same")
    L.append("// places, so a feature can be switched between them without a")
    L.append("// marshalling layer in the middle. Every field carries a")
    L.append("// _Static_assert, so an offset that drifts fails the build rather")
    L.append("// than corrupting state at runtime.")
    L.append("//")
    L.append("// Harness-only state does NOT belong here. Retail code runs over")
    L.append("// this memory; anything invented squatting on bytes we have not")
    L.append("// identified would be trampled, or would trample. Keep GLUE in a")
    L.append("// parallel struct keyed by the same index.")
    L.append("#ifndef BURNOUT3_VEHICLE_RETAIL_H")
    L.append("#define BURNOUT3_VEHICLE_RETAIL_H")
    L.append("")
    L.append("#include <stddef.h>")
    L.append("")
    L.append("#define B3_VEHICLE_RETAIL_SPAN 0x%04Xu" % SPAN)
    L.append("")
    L.append("// PACKED deliberately. Retail's layout has no alignment we")
    L.append("// control -- the wheel count is a byte at +0x1169, and a 4-byte")
    L.append("// field at a non-4-aligned offset makes the compiler insert its")
    L.append("// own padding and shift everything after it. Explicit padding")
    L.append("// only holds if the compiler adds none of its own.")
    L.append("typedef struct __attribute__((packed)) B3VehicleRetail {")
    cur = 0
    npad = 0
    for off, name, ctype, arr, sz in kept:
        if off > cur:
            L.append("    unsigned char _pad%02d[0x%X];" % (npad, off - cur))
            npad += 1
        L.append("    %-14s %s%s;%s// +0x%04X"
                 % (ctype, name, arr, " " * max(1, 22 - len(name) - len(arr)),
                    off))
        cur = off + sz
    if cur < SPAN:
        L.append("    unsigned char _pad%02d[0x%X];" % (npad, SPAN - cur))
    L.append("} B3VehicleRetail;")
    L.append("")
    L.append("_Static_assert(sizeof(B3VehicleRetail) == B3_VEHICLE_RETAIL_SPAN,")
    L.append("               \"vehicle span drifted\");")
    for off, name, _c, _a, _s in kept:
        L.append("_Static_assert(offsetof(B3VehicleRetail, %s) == 0x%04X,"
                 % (name, off))
        L.append("               \"%s moved off retail's offset\");" % name)
    L.append("")
    L.append("#endif // BURNOUT3_VEHICLE_RETAIL_H")

    open(a.out, "w").write("\n".join(L) + "\n")

    print("%d annotated field(s); %d placed, %d dropped"
          % (len(fields), len(kept), len(dropped)))
    if dropped:
        print("\nDROPPED -- these need a decision before the shape is real:")
        for off, name, sz, end in dropped:
            why = ("overlaps the field ending at 0x%04X" % end) if end >= 0 \
                  else "runs past the 0x%04X span" % SPAN
            print("  0x%04X %-26s (%2d B)  %s" % (off, name, sz, why))
    print("\nwrote %s" % os.path.relpath(a.out, ROOT))


if __name__ == "__main__":
    main()
