#!/usr/bin/env python3
"""Emit the byte ranges of B3VehicleFull that are RECOVERED.

Shape parity put our fields at retail's offsets, but the port models only the
fields we have recovered -- the rest of retail's 0x1A00 object is padding here,
and the emulator seeds real values there. Writing the whole window over the top
replaces that seed with zeros and hangs retail's substep loop.

So the transfer covers exactly the recovered ranges: same offset on both sides,
no field converted, and everything we have NOT recovered is left as the
emulator seeded it. This reads the parity assertions -- the same ones that
guarantee the offsets -- so the table cannot drift from the struct.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "burnout3_vehicle_sim.h")
OUT = os.path.join(ROOT, "src", "burnout3_vehicle_ranges.h")

SRC = open(HDR).read()

# NOTE the `(?:0x)?`. This pattern used to require a 0x prefix, and the rigid
# body is asserted as `offsetof(B3VehicleFull, rb) == 0` -- no prefix -- so the
# WHOLE BODY silently fell out of the transfer: velocity, heading, omega,
# angular momentum and all four accumulators. physics=retail was handing the
# game a vehicle with no motion state and taking back only the frame, which is
# position without the velocity that produced it.
HEX = r'_Static_assert\(offsetof\(%s,\s*(\w+)\)\s*==\s*(?:0x)?([0-9A-Fa-f]+)'
names = [(n, int(o, 16)) for n, o in re.findall(HEX % "B3VehicleFull", SRC)]

# The body is a nested struct, so it expands into ITS recovered fields rather
# than moving as one blob -- `frame` is a HOST POINTER (GLUE +0x140, retail
# keeps its own at v+0x204) and must never be written into the emulator.
RB_SKIP = {"frame"}
body = [(n, int(o, 16)) for n, o in re.findall(HEX % "B3RigidBody", SRC)
        if n not in RB_SKIP]
rb_off = dict(names).get("rb")
if rb_off is not None:
    names = [(n, o) for n, o in names if n != "rb"]
    names += [("rb." + n, rb_off + o) for n, o in body]
names.sort(key=lambda r: r[1])

# ---------------------------------------------------------------------------
# THE DRIVER BLOCK -- owned by whoever runs the DRIVER, not by the physics.
#
# b3_ai_drive writes its inputs AND its carried scratch straight into the
# vehicle (that is what removing the invented B3AiInputs bought). Under
# physics=retail the body is retail's, but the driver is still the port's, so
# mirroring these back over the port every frame wipes the slew memory at
# v+0x1408 and the dither/stuck timers at v+0x156C..0x157C. The AI then stops
# commanding throttle and the car coasts to a standstill with thr=0.00.
#
# Retail receives the live inputs as arguments to the step, so it never needs
# them mirrored back; and when ai=retail the AI bridge reads its own
# B3_AIVEH_RANGES. Excluded from the mirror in both cases.
DRIVER_OWNED = {"throttle_1400", "brake_1404", "steer_1408", "throttle_raw_1414",
                "input_bits_13FC", "prev_throttle_156C", "brake_hold_1570",
                "dither_1574", "stuck_arm_1578", "reverse_timer_157C"}


L = ["// GENERATED by tools/gen_vehicle_ranges.py -- do not edit by hand.",
     "//",
     "// The recovered byte ranges of B3VehicleFull, at retail's own offsets.",
     "// Built from the parity assertions, so it cannot drift from the struct.",
     "//",
     "// Used to hand retail our state without destroying the parts of its",
     "// vehicle object we have not recovered: each range is written at the SAME",
     "// offset on both sides, and everything else is left as the emulator",
     "// seeded it. No field is converted in either direction.",
     "#ifndef BURNOUT3_VEHICLE_RANGES_H",
     "#define BURNOUT3_VEHICLE_RANGES_H",
     "",
     "#include <stddef.h>",
     '#include "burnout3_vehicle_sim.h"',
     "",
     "typedef struct { unsigned off, len; } B3VehicleRange;",
     "",
     "#define B3_VEH_MEMBER_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))",
     "",
     "static const B3VehicleRange B3_VEHICLE_RANGES[] = {"]
for n, o in names:
    if n in DRIVER_OWNED:
        continue
    L.append("    { (unsigned)offsetof(B3VehicleFull, %s), B3_VEH_MEMBER_LEN(%s) },"
             % (n, n))
L += ["};",
      "#define B3_VEHICLE_STATE_RANGE_COUNT "
      "(sizeof(B3_VEHICLE_STATE_RANGES)/sizeof(B3_VEHICLE_STATE_RANGES[0]))"]

# ---------------------------------------------------------------------------
# THE HANDOVER SET.
#
# B3_VEHICLE_RANGES above is what we READ BACK: everything recovered, so the
# port mirrors whatever retail did. It is NOT what we may WRITE.
#
# A retail-owned step is a co-simulation, not a snapshot compare. Retail owns
# the vehicle while it drives it, so the port hands its state over ONCE and
# then only mirrors. Writing every frame is what dropped the car through the
# floor: these fields are retail's to compute, and the port's copies go stale
# the moment its own step stops running.
#
#   rb.inv_inertia_world  rebuilt every step as Rt*I0*R
#   rb.inv_frame          rebuilt every step from the frame
#   rb.force_acc/torque_acc/imp_force/imp_torque/deflection
#                         per-substep accumulators the integrator clears
#
# The struct's own comments already say "(rebuilt)" and "(cleared)" on every
# one of them -- the classification was in the tree, just never acted on.
DERIVED = {"rb.inv_inertia_world", "rb.inv_frame", "rb.force_acc",
           "rb.torque_acc", "rb.imp_force", "rb.imp_torque", "rb.deflection"}

L += ["",
      "// The state the port HANDS OVER when retail takes the wheel. Excludes",
      "// everything retail rebuilds or clears itself -- see gen_vehicle_ranges.py.",
      "static const B3VehicleRange B3_VEHICLE_STATE_RANGES[] = {"]
for n, _o in names:
    if n in DERIVED:
        continue
    L.append("    { (unsigned)offsetof(B3VehicleFull, %s), B3_VEH_MEMBER_LEN(%s) },"
             % (n, n))
L += ["};",
      "",
      "#define B3_VEHICLE_RANGE_COUNT "
      "(sizeof(B3_VEHICLE_RANGES) / sizeof(B3_VEHICLE_RANGES[0]))",
      "",
      "#endif // BURNOUT3_VEHICLE_RANGES_H"]
open(OUT, "w").write("\n".join(L) + "\n")
print("wrote %s: %d recovered range(s)" % (os.path.relpath(OUT, ROOT), len(names)))
