#!/usr/bin/env python3
"""Emit the vehicle fields FUN_0011AEF0 reads and writes.

The chassis-vs-world resolve's interface, as B3VehicleFull members so the
table is derived from the parity assertions and cannot drift.

The list comes from B3CrashVehicle, the port's fourth partial view of the
vehicle object -- 26 fields, every one of them at a vehicle offset that
B3VehicleFull already models. That view is built and written back on every
call by b3_vehicle_chassis_contact, so the RE path keeps it; the retail path
does not need it and works off B3VehicleFull directly.

Two of those 26 are worth naming:
  * v+0x1404 appears as `ground_frac` there and `brake_1404` here. One
    address, two names -- the bridge already writes `cv.ground_frac =
    v->brake_1404`. validate_ai pins it: retail's driver puts the BRAKE there
    (brk = rf(VEH+0x1404)), so brake_1404 is the name that matches the game.
  * v+0x020E (`asleep`) existed ONLY in that view and is now on the vehicle.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VH = os.path.join(ROOT, "src", "burnout3_vehicle_sim.h")
OUT = os.path.join(ROOT, "src", "burnout3_crash_ranges.h")

# B3CrashVehicle field  ->  the B3VehicleFull member at the same offset
IFACE = [
    ("rb.inv_inertia_world", 0x0040), ("rb.inv_frame", 0x0070),
    ("rb.vel", 0x00B0), ("rb.dir", 0x00C0), ("rb.omega", 0x00D0),
    ("rb.force_acc", 0x00F0), ("rb.imp_force", 0x0110),
    ("rb.imp_torque", 0x0120), ("rb.deflection", 0x0130),
    ("contact_pt_160", 0x0160), ("contact_n_170", 0x0170),
    ("surface_190", 0x0190), ("impact_194", 0x0194),
    ("contact_state_198", 0x0198), ("half_ext", 0x01D0),
    ("center_off", 0x01E0), ("mass", 0x01F0), ("asleep_020E", 0x020E),
    ("flags_1353", 0x1353), ("surface_grip_13A8", 0x13A8),
    ("brake_1404", 0x1404), ("drift_dir_1434", 0x1434),
    ("trans.gear", 0x14C8), ("drift_state_1524", 0x1524),
    ("authority_1534", 0x1534), ("no_scrub_153E", 0x153E),
]

src = open(VH).read()
for member, _off in IFACE:
    base = member.split(".")[0]
    if ("offsetof(B3VehicleFull, %s)" % base) not in src:
        raise SystemExit("crash iface: %s has no parity assertion" % member)

L = ["// GENERATED by tools/gen_crash_ranges.py -- do not edit by hand.",
     "//",
     "// The vehicle fields FUN_0011AEF0 (chassis-vs-world resolve) touches.",
     "// Each range is written at the SAME offset on both sides; nothing is",
     "// converted, and the rest of retail's vehicle stays as the emulator",
     "// seeded it -- including the veh+0x200 soup the resolve reads.",
     "#ifndef BURNOUT3_CRASH_RANGES_H",
     "#define BURNOUT3_CRASH_RANGES_H",
     "",
     "#include <stddef.h>",
     '#include "burnout3_vehicle_sim.h"',
     "",
     "typedef struct { unsigned off, len; } B3CrashRange;",
     "",
     "#define B3_CRASHVEH_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))",
     "static const B3CrashRange B3_CRASHVEH_RANGES[] = {"]
for member, off in sorted(IFACE, key=lambda r: r[1]):
    L.append("    { (unsigned)offsetof(B3VehicleFull, %s), B3_CRASHVEH_LEN(%s) },  // +0x%04X"
             % (member, member, off))
L += ["};",
      "#define B3_CRASHVEH_RANGES_COUNT "
      "(sizeof(B3_CRASHVEH_RANGES)/sizeof(B3_CRASHVEH_RANGES[0]))",
      "", "#endif // BURNOUT3_CRASH_RANGES_H", ""]
open(OUT, "w").write("\n".join(L))
print("  %s: %d range(s)" % (os.path.relpath(OUT, ROOT), len(IFACE)))
