#!/usr/bin/env python3
"""Emit the recovered byte ranges of the AI gather structs.

Same principle as gen_vehicle_ranges.py: each range is written at the SAME
offset on both sides, nothing is converted, and everything not recovered is
left as the emulator seeded it. Built from the parity assertions so the table
cannot drift from the structs.

The two structs go to DIFFERENT objects, and that is the whole point:

    B3AiCar    -> the racecar object   (RC + off)
    B3AiInputs -> the physics vehicle  (VEH + off)

B3AiCar used to carry ten vehicle fields at their VEHICLE offsets, so this
table sent them to RC+0xBC, RC+0x1470 and so on -- the wrong object. They were
duplicates of B3VehicleFull fields at identical offsets and have been removed;
B3AiCar now holds a pointer to the vehicle, exactly as retail does at
racecar+0x2440. The pointer is harness-side and therefore never appears here.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "burnout3_ai.h")
OUT = os.path.join(ROOT, "src", "burnout3_ai_ranges.h")

src = open(HDR).read()


def ranges(struct):
    got = re.findall(
        r'_Static_assert\(offsetof\(%s,\s*(\w+)\)\s*==\s*0x([0-9A-Fa-f]+)' % struct, src)
    return sorted(((n, int(o, 16)) for n, o in got), key=lambda r: r[1])


L = ["// GENERATED by tools/gen_ai_ranges.py -- do not edit by hand.",
     "//",
     "// Recovered byte ranges of the AI gather structs, at retail's offsets:",
     "//   B3AiCar   -> the racecar object            (RC + off)",
     "//   B3AiState -> the AI object EMBEDDED in it   (RC + 0x1A00 + off)",
     "//",
     "// The navigator ctor FUN_001705F0 writes the aggregate back-pointers at",
     "// racecar+0x1A04/0x21A0/0x2160, which is what places the AI object at",
     "// racecar+0x1A00. Its offsets are AI-relative, so the bias is applied at",
     "// the transfer, not baked into the struct.",
     "// The vehicle side needs no table here: the driver writes the physics",
     "// vehicle directly, so B3_VEHICLE_RANGES carries it.",
     "// Built from the parity assertions so they cannot drift from the structs.",
     "#ifndef BURNOUT3_AI_RANGES_H",
     "#define BURNOUT3_AI_RANGES_H",
     "",
     "#include <stddef.h>",
     '#include "burnout3_ai.h"',
     '#include "burnout3_vehicle_sim.h"',
     "",
     "typedef struct { unsigned off, len; } B3AiRange;"]

for struct, macro, tag in (("B3AiCar", "B3_AICAR", "AICAR"),
                           ("B3AiState", "B3_AISTATE", "AISTATE")):
    L += ["", "#define %s_LEN(f) ((unsigned)sizeof(((%s*)0)->f))" % (macro, struct),
          "static const B3AiRange %s_RANGES[] = {" % macro]
    for n, _o in ranges(struct):
        L.append("    { (unsigned)offsetof(%s, %s), %s_LEN(%s) }," % (struct, n, macro, n))
    L += ["};",
          "#define %s_RANGES_COUNT (sizeof(%s_RANGES)/sizeof(%s_RANGES[0]))"
          % (macro, macro, macro)]

# ---------------------------------------------------------------------------
# The DRIVER'S VEHICLE INTERFACE.
#
# Not the whole vehicle. FUN_00105340 reads and writes a specific set of
# fields, and handing it the full B3_VEHICLE_RANGES table instead is
# over-transfer -- the same "coverage, not just alignment" hazard that the
# all-zero window hit, from the other side: we overwrite state the emulator
# seeded coherently with state that is only coherent inside the port. Measured
# with the full table: 65 driver calls/s at ~15 ms each, the car crawling,
# against 82 game-seconds in 60 with this list.
#
# This IS the function's interface, and it is derived the same way everything
# else here is -- offsetof/sizeof over the parity-asserted struct, so a field
# that moves breaks the build rather than the transfer.
AIVEH = [
    # --- read: where the car is going ---
    "rb.vel",               # v+0x00B0, [3] = speed (v+0x00BC)
    "rb.dir",               # v+0x00C0  "carAt" heading
    "rb.omega",             # v+0x00D0, [1] = yaw rate (v+0x00D4)
    # --- read: the driver's gates ---
    "lsdm_limit_13AC",
    "trans.change_up_rpm",  # v+0x1470
    "trans.omega",          # v+0x149C rad/s
    "lsdm_active_1550",
    # --- read AND write ---
    "trans.gear",           # v+0x14C8
    "drift_state_1524",
    "authority_1534",
    "steer_1408",           # also the slew limiter's memory, carried in
    # --- write: the inputs the driver produces ---
    "input_bits_13FC",
    "throttle_1400",
    "brake_1404",
    "throttle_raw_1414",
    "stop_flag_1552",
    # --- write: the driver's own timers ---
    "prev_throttle_156C",
    "brake_hold_1570",
    "dither_1574",
    "stuck_arm_1578",
    "reverse_timer_157C",
]
VHDR = os.path.join(ROOT, "src", "burnout3_vehicle_sim.h")
vsrc = open(VHDR).read()
for m in AIVEH:
    base = m.split(".")[0]
    if ("offsetof(B3VehicleFull, %s)" % base) not in vsrc:
        raise SystemExit("AIVEH: %s has no parity assertion" % m)

L += ["", "// The vehicle fields FUN_00105340 actually reads and writes.",
      "#define B3_AIVEH_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))",
      "static const B3AiRange B3_AIVEH_RANGES[] = {"]
for m in AIVEH:
    L.append("    { (unsigned)offsetof(B3VehicleFull, %s), B3_AIVEH_LEN(%s) }," % (m, m))
L += ["};",
      "#define B3_AIVEH_RANGES_COUNT (sizeof(B3_AIVEH_RANGES)/sizeof(B3_AIVEH_RANGES[0]))"]

L += ["", "#endif // BURNOUT3_AI_RANGES_H", ""]
open(OUT, "w").write("\n".join(L))
L.insert(-2, "")
L.insert(-2, "// Retail embeds the AI object here; see FUN_001705F0.")
L.insert(-2, "#define B3_AI_OBJECT_OFFSET 0x1A00u")
open(OUT, "w").write("\n".join(L))
print("  %s: %d car range(s), %d AI-object range(s)"
      % (os.path.relpath(OUT, ROOT), len(ranges("B3AiCar")), len(ranges("B3AiState"))))
