#!/usr/bin/env python3
"""Emit the retail emitter behind each B3SfxEvent.

Built by matching two sources that already exist, so neither can drift alone:

  src/burnout3_sfx.h   the B3SfxEvent enum, each entry commented with the
                       emitter it reproduces (`FUN_0014F3E0  IMPACTNUDG ...`)
  tools/emulate_sfx.py EMITTERS -- the same addresses with the CALLING
                       CONVENTION each one needs ('ecx', 'eax_m8', ...), which
                       is the part the port's comment does not carry

An event whose address is not in EMITTERS gets addr 0 and is simply not
switchable: its emitter has no captured convention yet, so retail cannot be
asked what it would play, and b3_sfx_event stays on the port for that one.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = os.path.join(ROOT, "src", "burnout3_sfx.h")
EMU = os.path.join(ROOT, "tools", "emulate_sfx.py")
OUT = os.path.join(ROOT, "src", "burnout3_sfx_emitters.h")

KINDS = ["ecx", "eax_x0", "eax_m8", "st_obj_m8", "st4"]

emu = open(EMU).read()
i = emu.find("EMITTERS = [")
conv = {}
for m in re.finditer(r"\(0x([0-9A-Fa-f]{8}),\s*'([A-Z]+)',\s*'[^']*',\s*'(\w+)'",
                     emu[i:emu.find("\n]", i)]):
    conv[int(m.group(1), 16)] = (m.group(3), m.group(2))

src = open(HDR).read()
i = src.find("B3_SFX_IMPACT_NUDGE")
j = src.find("} B3SfxEvent;")
events = []
for line in src[i:j].split("\n"):
    m = re.match(r"\s*(B3_SFX_\w+)\s*(?:=\s*\d+)?\s*,\s*/\*\s*FUN_([0-9A-Fa-f]{8})", line)
    if m:
        events.append((m.group(1), int(m.group(2), 16)))
    else:
        m2 = re.match(r"\s*(B3_SFX_\w+)\s*(?:=\s*\d+)?\s*,", line)
        if m2:
            events.append((m2.group(1), 0))

L = ["// GENERATED by tools/gen_sfx_emitters.py -- do not edit by hand.",
     "//",
     "// The retail emitter behind each B3SfxEvent, with the calling",
     "// convention it needs. Address 0 = not switchable: no captured",
     "// convention for that emitter, so b3_sfx_event stays on the port.",
     "#ifndef BURNOUT3_SFX_EMITTERS_H",
     "#define BURNOUT3_SFX_EMITTERS_H",
     "",
     '#include "burnout3_sfx.h"',
     "",
     "typedef struct { unsigned addr; int kind; const char* wave; } B3SfxEmitter;",
     "",
     "// kind ids match tools/emulate_sfx.py's `fire(kind=...)` strings:"]
for n, k in enumerate(KINDS):
    L.append("//   %d = %s" % (n, k))
L.append("static const B3SfxEmitter B3_SFX_EMITTERS[] = {")
have = 0
for name, addr in events:
    kind, wave = conv.get(addr, (None, None))
    if kind is None:
        L.append("    { 0x0, -1, 0 },  // %s" % name)
    else:
        have += 1
        L.append("    { 0x%08X, %d, \"%s\" },  // %s"
                 % (addr, KINDS.index(kind), wave, name))
L += ["};",
      "#define B3_SFX_EMITTER_COUNT "
      "(sizeof(B3_SFX_EMITTERS)/sizeof(B3_SFX_EMITTERS[0]))",
      "", "#endif // BURNOUT3_SFX_EMITTERS_H", ""]
open(OUT, "w").write("\n".join(L))
print("  %s: %d event(s), %d with a callable emitter"
      % (os.path.relpath(OUT, ROOT), len(events), have))
