#!/usr/bin/env python3
"""Differential validation of the RUBBER BAND -- retail's player-relative AI
laws -- against the real x86 executed under Unicorn.

Same shape as tools/validate_ai.py: it compiles src/burnout3_ai.c itself into
a probe and diffs THAT against the retail instructions, so what is asserted is
the shipped C, not a paraphrase of it.

Functions under test (analyzed burnout3.elf, .text = flat + 0x10000):

  0x00106370  FUN_00106370  "where am I relative to my human player"
              -> vehicle +0x1554 (which player), +0x1558 (1 me / 2 ahead /
                 3 behind), +0x155C (gap, 0 at 40 m .. 1 at 140 m)
              vs b3_ai_player_rel()

  0x001734C0  FUN_001734C0  THE CATCH-UP
              -> returns the new AI+0x9C4 demand, writes AI+0x9DC (the
                 off-camera warp speed) and latches AI+0xA31 on expiry
              vs b3_ai_catchup()

  0x00173690  FUN_00173690  the hard speed cap
              -> AI+0xA08
              vs b3_ai_speed_cap()

WHY THIS EXISTS
---------------
docs/RE_AI.md 15.6 row 10b recorded FUN_001734C0 as "documented [S], not
ported", and tools/emulate_ai.py's seed_car() pins AI+0xA0C to 1e9 and
AI+0xA31 to 1 with the comment "keep the catch-up branch out unless asked".
Nothing in the suite had ever executed either law, and the port's call site
passed the literal 0.0f for the bonus.  This is the case set that was missing.

TWO STUBS, and why they are honest
----------------------------------
FUN_001734C0 calls FUN_00194380 (the along-track distance of a score object)
and FUN_00106370 calls FUN_00194200 (the lap/checkpoint/distance comparator).
Both walk objects this harness does not build, and both are pure inputs to the
laws under test -- the port takes them as arguments (`race_fraction`,
`ahead_of_player`).  Each is replaced in the emulated image by a 6..9 byte
stub that returns a value this script controls, so the CASE seeds both sides
identically and the diff is over the law, not over the input plumbing.

Run from the repo root:  python3 tools/validate_rubberband.py
"""
import os
import struct
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import emulate_ai as ea                                        # noqa: E402
from unicorn.x86_const import (UC_X86_REG_EAX, UC_X86_REG_EBX,  # noqa: E402
                               UC_X86_REG_ECX, UC_X86_REG_EDX,
                               UC_X86_REG_ESI, UC_X86_REG_EDI)

AI = ea.AI
RC = ea.RC
VEH = ea.VEH
TOL = 1e-5

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build")
PROBE_C = os.path.join(BUILD, "rb_probe.c")
PROBE = os.path.join(BUILD, "rb_probe")

# The probe links burnout3_backend.c; pin it to the RE path so a flipped
# build/backends.cfg cannot change what this suite measures.
os.environ['B3_BACKENDS'] = '/dev/null'

# --- addresses -------------------------------------------------------------
F_PLAYER_REL = 0x00106370        # -> vehicle +0x1554/+0x1558/+0x155C
F_CATCHUP    = 0x001734C0        # -> AI+0x9C4 return, AI+0x9DC, AI+0xA31
F_SPEED_CAP  = 0x00173690        # -> AI+0xA08
F_TRACK_DIST = 0x00194380        # stubbed: along-track distance
F_OUTRANKS   = 0x00194200        # stubbed: does a outrank b?

G_NCARS_A19C = 0x0073A19C        # count for the DAT_0073A1A8 pointer table
G_CARTAB     = 0x0073A1A8        # the car POINTER table FUN_001734C0 walks
G_NCARS_A1C0 = 0x0073A1C0        # count for the DAT_0073A1D0 object ARRAY
G_CARARRAY   = 0x0073A1D0        # the racecar array, stride 0x27E0
G_SECTIONS   = 0x0073A164        # per-section factor table (0 = none)
G_LAPLEN     = 0x0073A184        # {f32 cumulative length, ...} stride 8
G_LAPLEN_N   = 0x0073A188
G_DIFF_IDX   = 0x0073BB50        # BSS, never written -> place window = 1
G_DIFF_TAB   = 0x003A29EC        # {1,1,2,2,3,3,1}
CAR_STRIDE   = 0x27E0

# scratch for the stubs' return values
STUB_DIST    = 0x0073BC00        # f32 FUN_00194380 returns
STUB_RANK    = 0x0073BC08        # u32 FUN_00194200 returns (in EAX)
OTHER        = ea.OTHER          # 0x70000000, 0x10000 -- the other cars
OTHER_STRIDE = 0x2000            # > 0x1924, the highest offset we touch
LAPTAB       = OTHER + 0x6000    # the {f32 cumulative length, ...} array
PLAYER_VEH   = OTHER + 0x4000    # the paired player's physics vehicle

TOP_SPEED = ea.VDB[ea.P_TOP_SPEED]     # 88.0
MIN_SPEED = ea.VDB[ea.P_MIN_SPEED]     # 20.0

# retail constants, for the report only -- the C reads its own copies
C_RELEASE = 45.0
C_WARP    = 17.8816
C_MARGIN  = 4.4704


# ===========================================================================
# The probe: a key=value driver around the real module.
# ===========================================================================
PROBE_SRC = r'''
/* GENERATED by tools/validate_rubberband.py -- a key=value driver around the
 * shipped src/burnout3_ai.c so the differential suite tests the C. */
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include "%(AI_SRC)s"

static B3AiState S;
static B3VehicleFull V;
static float VFRAME[4][4];

#define MAXC 8
static int   g_place[MAXC], g_mode[MAXC];
static B3AiCatchupIn IN;
static float g_spd, g_player_speed, g_sec_min, g_sec_max, g_ret;
static float g_d2, g_gap;
static int   g_race_mode, g_ncars, g_grid, g_ahead, g_pslot, g_rank;

typedef struct { const char* n; void* p; int isint; } Bind;
static const Bind BINDS[] = {
    /* FUN_001734C0 / FUN_00173690 inputs (B3AiCatchupIn) */
    {"frac",     &IN.race_fraction, 0},
    {"distok",   &IN.dist_valid,    1},
    {"m2450",    &IN.mode_2450,     1},
    {"vok",      &IN.veh_valid,     1},
    {"inrange",  &IN.veh_in_range,  1},
    {"rank",     &IN.veh_rank,      1},
    {"gapn",     &IN.veh_gap_norm,  0},
    {"myplace",  &IN.my_place,      1},
    {"window",   &IN.place_window,  1},
    {"ncars",    &IN.ncars,         1},
    /* persistent AI state */
    {"cwin",     &S.catchup_window, 0},
    {"expired",  &S.catchup_expired, -1},   /* byte */
    {"a04",      &S.pace_a04,       0},
    {"cap",      &S.speed_cap,      0},
    {"bonus",    &S.catchup_bonus,  0},
    /* scalars */
    {"spd",      &g_spd,            0},
    {"pspeed",   &g_player_speed,   0},
    {"secmin",   &g_sec_min,        0},
    {"secmax",   &g_sec_max,        0},
    /* FUN_00106370 inputs */
    {"rmode",    &g_race_mode,      1},
    {"nc",       &g_ncars,          1},
    {"grid",     &g_grid,           1},
    {"ahead",    &g_ahead,          1},
    {"d2",       &g_d2,             0},
    /* retail-side only: which DAT_0073A1D0 slot the paired player is.  The
     * port resolves the player's speed for the caller, so the C never reads
     * it -- the bind exists so the shared case dict parses. */
    {"pslot",    &g_pslot,          1},
    {NULL, NULL, 0}
};

static void set_kv(const char* k, const char* v) {
    int i;
    if (!strncmp(k, "place", 5) && k[5]) {
        int idx = atoi(k + 5);
        if (idx >= 0 && idx < MAXC) g_place[idx] = atoi(v);
        return;
    }
    if (!strncmp(k, "mode", 4) && k[4]) {
        int idx = atoi(k + 4);
        if (idx >= 0 && idx < MAXC) g_mode[idx] = atoi(v);
        return;
    }
    for (i = 0; BINDS[i].n; i++) {
        if (strcmp(BINDS[i].n, k)) continue;
        if (BINDS[i].isint == 1)       *(int*)BINDS[i].p   = atoi(v);
        else if (BINDS[i].isint == -1) *(unsigned char*)BINDS[i].p =
                                            (unsigned char)atoi(v);
        else                            *(float*)BINDS[i].p = (float)atof(v);
        return;
    }
    fprintf(stderr, "unknown key %%s\n", k);
    exit(2);
}

int main(int argc, char** argv) {
    int i;
    const char* op = "catchup";
    memset(&S, 0, sizeof S); memset(&V, 0, sizeof V);
    memset(&IN, 0, sizeof IN); memset(&g_place, 0, sizeof g_place);
    memset(&g_mode, 0, sizeof g_mode);
    V.rb.frame = VFRAME;
    S.catchup_gate = -1.0f;
    IN.place = g_place; IN.race_mode = g_mode;
    g_sec_min = %(MIN_SPEED)ff; g_sec_max = %(TOP_SPEED)ff;
    b3_ai_params.top_speed_mps = %(TOP_SPEED)ff;
    b3_ai_params.min_speed_mps = %(MIN_SPEED)ff;
    for (i = 1; i < argc; i++) {
        char* eq = strchr(argv[i], '=');
        if (!eq) { op = argv[i]; continue; }
        *eq = 0; set_kv(argv[i], eq + 1);
    }
    if (!strcmp(op, "catchup")) {
        g_ret = b3_ai_catchup(&S, &IN, g_spd);
        printf("ret=%%.7g bonus=%%.7g expired=%%d a04=%%.7g\n",
               (double)g_ret, (double)S.catchup_bonus,
               (int)S.catchup_expired, (double)S.pace_a04);
    } else if (!strcmp(op, "cap")) {
        b3_ai_speed_cap(&S, &IN, g_player_speed, g_sec_min, g_sec_max);
        printf("cap=%%.7g\n", (double)S.speed_cap);
    } else if (!strcmp(op, "rel")) {
        g_pslot = -1; g_rank = -1; g_gap = -1.0f;
        b3_ai_player_rel(g_race_mode, g_ncars, g_grid, g_ahead, g_d2,
                         &g_pslot, &g_rank, &g_gap);
        printf("pslot=%%d rank=%%d gap=%%.7g\n", g_pslot, g_rank,
               (double)g_gap);
    } else {
        fprintf(stderr, "unknown op %%s\n", op);
        return 2;
    }
    return 0;
}
'''


def build_probe(ai_src):
    os.makedirs(BUILD, exist_ok=True)
    with open(PROBE_C, "w") as f:
        f.write(PROBE_SRC % {"AI_SRC": ai_src,
                             "TOP_SPEED": TOP_SPEED,
                             "MIN_SPEED": MIN_SPEED})
    cmd = ["gcc", "-std=c11", "-O1", "-I", os.path.join(ROOT, "src"),
           "-I", os.path.dirname(ai_src),
           "-Wno-address-of-packed-member",
           PROBE_C,
           os.path.join(ROOT, "src", "burnout3_backend.c"),
           os.path.join(ROOT, "src", "burnout3_emu.c"),
           "-lm", "-o", PROBE]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        sys.exit("probe build failed:\n" + r.stdout + r.stderr)


def run_probe(op, seeds):
    args = [PROBE, op] + ["%s=%s" % (k, v) for k, v in sorted(seeds.items())]
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode:
        sys.exit("probe failed (%s): %s%s" % (op, r.stdout, r.stderr))
    out = {}
    for tok in r.stdout.split():
        k, _, v = tok.partition('=')
        out[k] = float(v)
    return out


# ===========================================================================
# The retail side.
# ===========================================================================
def install_stubs(s):
    """Replace the two pure-input helpers with constant returns.

    FUN_00194380 -> XMM0 = [STUB_DIST]        (movss xmm0,[imm32]; ret)
    FUN_00194200 -> EAX  = [STUB_RANK]        (mov eax,[imm32]; ret)
    Neither takes stack arguments at the call sites under test, so a plain
    `ret` is the right epilogue for both.
    """
    s.uc.mem_write(F_TRACK_DIST,
                   b"\xF3\x0F\x10\x05" + struct.pack('<I', STUB_DIST) + b"\xC3")
    s.uc.mem_write(F_OUTRANKS,
                   b"\xA1" + struct.pack('<I', STUB_RANK) + b"\xC3")


def new_session():
    s = ea.Session()
    ea.seed_car(s)
    install_stubs(s)
    # no per-section factor table -> FUN_00172BC0 returns "Min speed mps"
    # (@0x00172D05) and FUN_00172D20 returns "Top speed mps" (@0x00172E65)
    s.wu(G_SECTIONS, 0)
    # the difficulty index is BSS and referenced by exactly one instruction in
    # the whole image (the read at 0x001735AC); it is never written.
    s.wu(G_DIFF_IDX, 0)
    for i, v in enumerate((1, 1, 2, 2, 3, 3, 1)):
        s.wi(G_DIFF_TAB + i * 4, v)
    # laps * cumulative length.  DAT_0073A184 is a POINTER to a stride-8
    # record array and DAT_0073A188 the section count; the operand at
    # 0x00173532 is `[edx + eax*8 - 8]`, i.e. the LAST section's cumulative
    # length -- the whole lap.  One section, 1000 m.
    s.wu(G_LAPLEN, LAPTAB)
    s.wu(G_LAPLEN_N, 1)
    s.wf(LAPTAB, 1000.0)
    return s


def seed_cars(s, places, modes):
    """Lay the other cars out in OTHER and publish the pointer table."""
    s.wu(G_NCARS_A19C, len(places))
    for i, (p, m) in enumerate(zip(places, modes)):
        base = OTHER + i * OTHER_STRIDE
        s.uc.mem_write(G_CARTAB + i * 4, struct.pack('<I', base))
        s.uc.mem_write(base + 0x10D0, struct.pack('<h', p))
        s.wi(base + 0x1920, m)


def retail_catchup(case):
    s = new_session()
    seed_cars(s, case["places"], case["modes"])
    s.uc.mem_write(RC + 0x10D0, struct.pack('<h', case["myplace"]))
    s.wi(RC + 0x2450, case["m2450"])
    s.wu(RC + 0x2440, VEH if case["vok"] else 0)
    s.wb(VEH + 0x1550, 1 if case["inrange"] else 0)
    s.wi(VEH + 0x1558, case["rank"])
    s.wf(VEH + 0x155C, case["gapn"])
    # the race fraction: (stub_dist - rc+0x135C) / (rc+0x1394 * 1000)
    if case["distok"]:
        s.wf(RC + 0x135C, 0.0)
        s.wi(RC + 0x1394, 1)
        s.wf(STUB_DIST, case["frac"] * 1000.0)
    else:
        s.wf(RC + 0x135C, -1.0)
        s.wi(RC + 0x1394, 0)
    s.wf(AI + 0x9E8, case["cwin"])
    s.wb(AI + 0xA31, case["expired"])
    s.wf(AI + 0xA04, 123.0)
    s.wf(AI + 0x9DC, -1.0)
    ret = s.call(F_CATCHUP, stack_args=(AI, ea.f2u(case["spd"])))
    return ({"ret": ret,
             "bonus": s.rf(AI + 0x9DC),
             "expired": float(s.rb(AI + 0xA31)),
             "a04": s.rf(AI + 0xA04)}, s.fault)


def retail_cap(case):
    s = new_session()
    s.wu(RC + 0x2440, VEH if case["vok"] else 0)
    s.wb(VEH + 0x1550, 1 if case["inrange"] else 0)
    s.wi(VEH + 0x1558, case["rank"])
    s.wb(VEH + 0x1554, case["pslot"])
    s.wb(AI + 0xA31, case["expired"])
    s.wb(AI + 0xA10, 0xFF)     # no section cursor -> the no-table returns
    # DAT_0073A1D0[pslot] -> +0x2440 -> the player's vehicle, +0xBC its speed
    s.wi(G_NCARS_A1C0, max(1, case["pslot"] + 1))
    pveh = PLAYER_VEH
    s.wu(G_CARARRAY + case["pslot"] * CAR_STRIDE + 0x2440, pveh)
    s.wf(pveh + 0xBC, case["pspeed"])
    s.wf(AI + 0xA08, -1.0)
    s.call(F_SPEED_CAP, stack_args=(AI,))
    return ({"cap": s.rf(AI + 0xA08)}, s.fault)


def retail_rel(case):
    s = new_session()
    s.wi(RC + 0x1920, case["rmode"])
    s.wi(G_NCARS_A1C0, case["nc"])
    s.wb(RC + 0x19BC, case["grid"])
    s.wb(RC + 0x27D0, case["grid"])
    s.wu(STUB_RANK, 1 if case["ahead"] else 0)
    # vehicle+0x1560[k]: FUN_00105BD0's squared-distance cache
    for k in range(4):
        s.wf(VEH + 0x1560 + k * 4, case["d2"])
    s.wb(VEH + 0x1554, 0x7F)
    s.wi(VEH + 0x1558, -1)
    s.wf(VEH + 0x155C, -1.0)
    s.call(F_PLAYER_REL, regs={UC_X86_REG_ESI: VEH})
    ps = s.rb(VEH + 0x1554)
    if ps >= 0x80:
        ps -= 0x100
    return ({"pslot": float(ps),
             "rank": float(s.ri(VEH + 0x1558)),
             "gap": s.rf(VEH + 0x155C)}, s.fault)


# ===========================================================================
# Cases.
# ===========================================================================
def catchup_case(name, **kw):
    c = dict(name=name, places=[1, 2], modes=[0, 1], myplace=2, m2450=0,
             vok=1, inrange=1, rank=3, gapn=0.0, distok=1, frac=0.0,
             cwin=0.8, expired=0, spd=40.0, window=1, a04=123.0)
    c.update(kw)
    return c


CATCHUP_CASES = [
    # -- the window is open and the player is exactly one place ahead --------
    catchup_case("player 1 place ahead, mid race"),
    catchup_case("player 1 place ahead, big gap", gapn=1.0),
    catchup_case("player 1 place ahead, half gap", gapn=0.5),
    catchup_case("player 1 place ahead, high demand", spd=70.0),
    # -- the player is further ahead than the window ------------------------
    catchup_case("player 2 places ahead", places=[1, 2, 3],
                 modes=[0, 1, 1], myplace=3),
    # -- the player is BEHIND me: rank 2, no catch-up ------------------------
    catchup_case("I lead the player", rank=2, places=[1, 2], modes=[1, 0],
                 myplace=1),
    catchup_case("rank 2 but player one place ahead", rank=2),
    # -- expiry --------------------------------------------------------------
    catchup_case("fraction past the window -> latch", frac=0.9, cwin=0.8),
    catchup_case("fraction exactly at the window", frac=0.8, cwin=0.8),
    catchup_case("fraction just under the window", frac=0.79, cwin=0.8),
    catchup_case("zero window expires immediately", cwin=0.0, frac=0.0),
    catchup_case("no distance -> fraction 0", distok=0, cwin=0.5),
    # -- off camera ----------------------------------------------------------
    catchup_case("off camera -> Top speed + 45", inrange=0),
    # `racecar+0x2440 == 0` is NOT tested here on purpose.  FUN_001734C0 has
    # an explicit null test at 0x0017362D, but BOTH paths that reach it have
    # already dereferenced the pointer -- `[EDI+0x1558]` at 0x0017359F and
    # `[ECX+0x1558]` at 0x0017358B -- so a null vehicle faults before the test
    # runs.  Same shape in FUN_00173690 (`[EDX+0x1558]` at 0x00173765 sits
    # BELOW the null check at 0x001736B6).  The test is dead code: every
    # racecar has a vehicle.  The port keeps the 0x00173671 arm anyway,
    # because that is the instruction stream; it is simply unreachable.
    # -- racecar+0x2450 == 1 skips the place test ---------------------------
    catchup_case("mode 2450=1, rank 3", m2450=1, places=[1, 2], modes=[0, 1],
                 myplace=1),
    catchup_case("mode 2450=1, rank 2", m2450=1, rank=2),
    catchup_case("mode 2450=2 is neither arm", m2450=2),
    # -- table walk edge cases ----------------------------------------------
    catchup_case("six cars, player 1 ahead",
                 places=[1, 2, 3, 4, 5, 6], modes=[1, 1, 0, 1, 1, 1],
                 myplace=4),
    catchup_case("six cars, player 2 ahead",
                 places=[1, 2, 3, 4, 5, 6], modes=[1, 0, 1, 1, 1, 1],
                 myplace=4),
    catchup_case("six cars, player behind me",
                 places=[1, 2, 3, 4, 5, 6], modes=[1, 1, 1, 1, 0, 1],
                 myplace=4),
    catchup_case("leader has nobody ahead", myplace=1, places=[1, 2],
                 modes=[1, 0]),
    catchup_case("no cars in the table", places=[], modes=[]),
]


def cap_case(name, **kw):
    c = dict(name=name, vok=1, inrange=1, rank=3, expired=0, pslot=0,
             pspeed=60.0)
    c.update(kw)
    return c


CAP_CASES = [
    cap_case("catch-up still armed -> Top speed"),
    cap_case("expired, fast player", expired=1, pspeed=60.0),
    cap_case("expired, slow player -> section min", expired=1, pspeed=10.0),
    cap_case("expired, player at the floor", expired=1,
             pspeed=MIN_SPEED + C_MARGIN),
    cap_case("expired, stopped player", expired=1, pspeed=0.0),
    cap_case("expired, very fast player", expired=1, pspeed=85.0),
    cap_case("expired, player slot 1", expired=1, pslot=1, pspeed=45.0),
    cap_case("off camera, ahead of player -> section min", inrange=0, rank=2),
    cap_case("off camera, behind player -> section max", inrange=0, rank=3),
    cap_case("off camera, expired, ahead", inrange=0, rank=2, expired=1),
]


def rel_case(name, **kw):
    c = dict(name=name, rmode=1, nc=6, grid=3, ahead=0, d2=0.0)
    c.update(kw)
    return c


REL_CASES = [
    rel_case("the human car itself", rmode=0, grid=0),
    rel_case("the human car, slot 1", rmode=0, grid=1),
    rel_case("AI behind its player, on top of it", d2=0.0),
    rel_case("AI behind, 40 m away -> gap 0", d2=40.0 * 40.0),
    rel_case("AI behind, 41 m away", d2=41.0 * 41.0),
    rel_case("AI behind, 100 m away", d2=100.0 * 100.0),
    rel_case("AI behind, 140 m away -> gap 1", d2=140.0 * 140.0),
    rel_case("AI behind, 300 m away -> clamped", d2=300.0 * 300.0),
    rel_case("AI ahead of its player", ahead=1, d2=100.0 * 100.0),
    rel_case("odd grid slot pairs with player 1", grid=5, d2=90.0 * 90.0),
    rel_case("even grid slot pairs with player 0", grid=4, d2=90.0 * 90.0),
    rel_case("single car in the world", nc=1, grid=5, d2=90.0 * 90.0),
]


def close(a, b):
    if a == b:
        return True
    d = abs(a - b)
    return d <= TOL or d <= TOL * max(abs(a), abs(b))


def main():
    ai_src = os.path.join(ROOT, "src", "burnout3_ai.c")
    for i, a in enumerate(sys.argv):
        if a == "--ai-src" and i + 1 < len(sys.argv):
            ai_src = os.path.abspath(sys.argv[i + 1])
    build_probe(ai_src)

    groups = (("FUN_00106370  player-relative block", REL_CASES, retail_rel,
               "rel", ("pslot", "rank", "gap")),
              ("FUN_001734C0  the catch-up", CATCHUP_CASES, retail_catchup,
               "catchup", ("ret", "bonus", "expired", "a04")),
              ("FUN_00173690  the hard speed cap", CAP_CASES, retail_cap,
               "cap", ("cap",)))

    npass = nfail = 0
    for title, cases, runner, op, fields in groups:
        print("\n=== %s ===" % title)
        for c in cases:
            want, fault = runner(c)
            if fault:
                print("  FAULT %-44s %s" % (c["name"], fault))
                nfail += 1
                continue
            seeds = {k: v for k, v in c.items()
                     if k not in ("name", "places", "modes")}
            if op == "catchup":
                for i, p in enumerate(c["places"]):
                    seeds["place%d" % i] = p
                for i, m in enumerate(c["modes"]):
                    seeds["mode%d" % i] = m
                seeds["ncars"] = len(c["places"])
            got = run_probe(op, seeds)
            bad = [f for f in fields if not close(got.get(f, 1e30), want[f])]
            if bad:
                nfail += 1
                print("  FAIL  %-44s %s" % (c["name"],
                      " ".join("%s retail=%.6g port=%.6g"
                               % (f, want[f], got.get(f, float('nan')))
                               for f in bad)))
            else:
                npass += 1
                print("  ok    %-44s %s" % (c["name"],
                      " ".join("%s=%.6g" % (f, want[f]) for f in fields)))

    print("\n%d/%d cases match retail" % (npass, npass + nfail))

    # ---- the behavioural assertion the report is about --------------------
    print("\n=== the catch-up RESPONSE to the player's lead ===")
    print("  a rival one place behind the player, window open:")
    base = catchup_case("probe")
    prev = None
    ok = True
    for gap_m in (0.0, 40.0, 60.0, 80.0, 100.0, 120.0, 140.0, 200.0):
        rel = retail_rel(rel_case("g", d2=gap_m * gap_m))[0]
        c = dict(base, gapn=rel["gap"])
        want, _ = retail_catchup(c)
        seeds = {k: v for k, v in c.items()
                 if k not in ("name", "places", "modes")}
        for i, p in enumerate(c["places"]):
            seeds["place%d" % i] = p
        for i, m in enumerate(c["modes"]):
            seeds["mode%d" % i] = m
        seeds["ncars"] = len(c["places"])
        got = run_probe("catchup", seeds)
        agree = close(got["bonus"], want["bonus"]) and close(got["ret"],
                                                             want["ret"])
        ok &= agree
        print("    %5.0f m  warp %6.3f m/s (%5.1f mph)  demand %5.1f -> %5.1f"
              "   %s" % (gap_m, want["bonus"], want["bonus"] * 2.2369363,
                         c["spd"], want["ret"],
                         "match" if agree else "MISMATCH"))
        if prev is not None and want["bonus"] < prev - TOL:
            ok = False
            print("      NOT MONOTONIC in the gap")
        prev = want["bonus"]
    if prev is None or prev <= 0.0:
        ok = False
    print("  monotonic non-decreasing in the gap, both backends: %s"
          % ("yes" if ok else "NO"))
    if not ok:
        nfail += 1

    print("\n=== the speed cap's RESPONSE to the player's speed ===")
    print("  a rival whose catch-up has expired:")
    prev = None
    ok2 = True
    for ps in (0.0, 10.0, 20.0, 30.0, 45.0, 60.0, 80.0):
        c = cap_case("g", expired=1, pspeed=ps)
        want, _ = retail_cap(c)
        seeds = {k: v for k, v in c.items() if k != "name"}
        got = run_probe("cap", seeds)
        agree = close(got["cap"], want["cap"])
        ok2 &= agree
        print("    player %5.1f m/s -> rival ceiling %5.1f m/s   %s"
              % (ps, want["cap"], "match" if agree else "MISMATCH"))
        if prev is not None and want["cap"] < prev - TOL:
            ok2 = False
        prev = want["cap"]
    print("  ceiling tracks the player's speed on both backends: %s"
          % ("yes" if ok2 else "NO"))
    if not ok2:
        nfail += 1

    if nfail:
        print("\n%d FAILURES" % nfail)
        return 1
    print("\nALL GREEN")
    return 0


if __name__ == "__main__":
    sys.exit(main())
