#!/usr/bin/env python3
"""Differential validation of the recovered AI AVOIDANCE stage
(src/burnout3_ai_avoid.c) against the real x86 executed under Unicorn.

Like tools/validate_ai.py this does NOT compare against a Python mirror of
the rule: it compiles src/burnout3_ai_avoid.c itself into a probe
(build/avoid_probe) and diffs THAT against the retail instructions.  Every
expected value below came out of executed retail, never out of a reading of
the decompiler.

Functions under test (analyzed burnout3.elf, .text = flat + 0x10000):
  0x00170260  the profile FRAME     -> avoid+0x00/0x10/0x20/0x30/0x444..0x44C
  0x00170100  the car's own FOOTPRINT band -> avoid+0x440/0x441/0x442
  0x0016F400  the world -> strip map and the strip stamp
  0x0016FCD0  the risk query at a strip
  0x0016F000  the clear-path aim strip
  0x0016C4B0  the chooser -> state, avoidance speed, dmin ladder, risks

Evidence notes: docs/RE_AI.md section 15 (and the corrections this suite
forced -- see docs/RE_SHAPE_PARITY.md).
Run from the repo root:  python3 tools/validate_ai_avoid.py
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import emulate_ai_avoid as ea                                  # noqa: E402
from unicorn.x86_const import UC_X86_REG_ESI                   # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, "build")
PROBE_C = os.path.join(BUILD, "avoid_probe.c")
PROBE = os.path.join(BUILD, "avoid_probe")

TOL = 2e-4
F_CHOOSE = 0x0016C4B0

PROBE_SRC = r'''
/* GENERATED by tools/validate_ai_avoid.py -- a key=value driver around the
 * shipped src/burnout3_ai_avoid.c so the differential suite tests the C,
 * not a paraphrase of it. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../src/burnout3_ai_avoid.c"

static B3AiAvoid A;
static float L[3], R[3], C[3];
static float RF[3], RR[3], CF[3];
static float g_len = 4.5f, g_wid = 2.0f;
static float g_ceiling = 55.0f;
static int   g_mode = 0;
static int   g_query = 128;

static void set3(float* d, const char* v) {
    sscanf(v, "%f,%f,%f", d, d + 1, d + 2);
}

int main(int argc, char** argv) {
    char line[512];
    b3_avoid_clear(&A);
    A.spd_gate = 30.0f;
    for (int i = 1; i < argc; i++) {
        char* eq = strchr(argv[i], '=');
        if (!eq) continue;
        *eq = 0;
        const char* k = argv[i];
        const char* v = eq + 1;
        if      (!strcmp(k, "left"))  set3(L, v);
        else if (!strcmp(k, "right")) set3(R, v);
        else if (!strcmp(k, "car"))   set3(C, v);
        else if (!strcmp(k, "rfwd"))  set3(RF, v);
        else if (!strcmp(k, "rright"))set3(RR, v);
        else if (!strcmp(k, "cfwd"))  set3(CF, v);
        else if (!strcmp(k, "len"))   g_len = atof(v);
        else if (!strcmp(k, "wid"))   g_wid = atof(v);
        else if (!strcmp(k, "ceiling")) g_ceiling = atof(v);
        else if (!strcmp(k, "mode"))  g_mode = atoi(v);
        else if (!strcmp(k, "gate"))  A.spd_gate = atof(v);
        else if (!strcmp(k, "query")) g_query = atoi(v);
        else if (!strcmp(k, "frame")) {
            b3_avoid_frame(&A, L, R, C);
        }
        else if (!strcmp(k, "band")) {
            /* (ext_w, ext_l) = (racecar+0x2444, racecar+0x2448) */
            b3_avoid_band(&A, RF, RR, CF, g_wid, g_len);
        }
        else if (!strcmp(k, "paintw")) {          /* two world points */
            float pl[3], pr[3]; int kind; float t, d;
            sscanf(v, "%f,%f,%f:%f,%f,%f:%d:%f:%f",
                   pl, pl + 1, pl + 2, pr, pr + 1, pr + 2, &kind, &t, &d);
            b3_avoid_paint(&A, pl, pr, kind, t, d);
        }
        else if (!strcmp(k, "paints")) {          /* strip span */
            int lo, hi, kind; float t, d;
            sscanf(v, "%d:%d:%d:%f:%f", &lo, &hi, &kind, &t, &d);
            b3_avoid_paint_span(&A, lo, hi, kind, t, d);
        }
        else if (!strcmp(k, "choose")) {
            b3_avoid_choose(&A, &B3_AI_AVOID_VDB, g_ceiling, g_mode);
        }
    }
    printf("width=%.7g\n", A.width);
    printf("axis=%.7g,%.7g,%.7g\n", A.axis[0], A.axis[1], A.axis[2]);
    printf("lat_left=%.7g\n", A.lat_left);
    printf("lat_right=%.7g\n", A.lat_right);
    printf("lo=%d\nhi=%d\nwin=%d\n", A.lo, A.hi, A.win);
    {
        int i, first = -1, last = -1;
        for (i = 0; i < B3_AV_N; i++) if (A.type[i]) { if (first < 0) first = i; last = i; }
        printf("span=%d,%d\n", first, last);
    }
    { int i; printf("timeq=");
      for (i = 0; i < B3_AV_N; i++) printf("%d%s", A.time[i], i == B3_AV_N-1 ? "\n" : ",");
      printf("distq=");
      for (i = 0; i < B3_AV_N; i++) printf("%d%s", A.dist[i], i == B3_AV_N-1 ? "\n" : ",");
      printf("typeq=");
      for (i = 0; i < B3_AV_N; i++) printf("%d%s", A.type[i], i == B3_AV_N-1 ? "\n" : ",");
    }
    {
        float m, t, x;
        b3_avoid_query(&A, g_query, &m, &t, &x);
        printf("q_mean=%.7g\nq_total=%.7g\nq_max=%.7g\n", m, t, x);
    }
    printf("aimstrip=%d\n", b3_avoid_aim_strip(&A));
    printf("state=%d\n", A.state);
    printf("speed=%.7g\n", A.speed);
    printf("dmin=%.7g\n", A.dmin);
    printf("frac=%.7g\n", A.frac);
    printf("rmean_r=%.7g\n", A.risk_mean_r);
    printf("rmean_l=%.7g\n", A.risk_mean_l);
    printf("rtot_r=%.7g\n", A.risk_tot_r);
    printf("rtot_l=%.7g\n", A.risk_tot_l);
    (void)line;
    return 0;
}
'''


def build_probe():
    if not os.path.isdir(BUILD):
        os.makedirs(BUILD)
    with open(PROBE_C, 'w') as f:
        f.write(PROBE_SRC)
    r = subprocess.run(["cc", "-O1", "-g", "-o", PROBE, PROBE_C, "-lm"],
                       capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("probe build failed")


def run_probe(args):
    r = subprocess.run([PROBE] + args, capture_output=True, text=True)
    if r.returncode:
        sys.stderr.write(r.stdout + r.stderr)
        raise SystemExit("probe run failed")
    out = {}
    for line in r.stdout.strip().splitlines():
        k, _, v = line.partition('=')
        out[k] = v
    return out


# ---------------------------------------------------------------------------
FAILS = []
NCASE = [0]


def chk(name, field, got, want, tol=TOL):
    NCASE[0] += 1
    if isinstance(want, float) or isinstance(got, float):
        ok = abs(float(got) - float(want)) <= tol * max(1.0, abs(float(want)))
    else:
        ok = got == want
    if not ok:
        FAILS.append("%-46s %-12s got %s want %s" % (name, field, got, want))
    return ok


class Case(object):
    """One seeded world, run on both sides."""

    def __init__(self, name, width=16.0, car_lat=0.0, car_fwd=(0, 0, 1),
                 car_right=(1, 0, 0), road_fwd=(0, 0, 1),
                 road_right=(1, 0, 0), car_len=4.5, car_wid=2.0,
                 gate=30.0, ceiling=55.0, mode=0, query=128, paints=()):
        self.name = name
        self.width = width
        self.car_lat = car_lat
        self.car_fwd = car_fwd
        self.car_right = car_right
        self.road_fwd = road_fwd
        self.road_right = road_right
        self.car_len = car_len
        self.car_wid = car_wid
        self.gate = gate
        self.ceiling = ceiling
        self.mode = mode
        self.query = query
        self.paints = paints          # (lo, hi, kind, time, dist) strip spans

    # --- retail -------------------------------------------------------
    def retail(self):
        s = ea.Session()
        entry = s.straight_road(width=self.width, n=64, spacing=10.0)
        # the car sits `car_lat` metres LEFT of the right edge, i.e. at
        # world x = +w/2 - car_lat given the road runs -w/2 (left) .. +w/2
        pos = (self.width * 0.5 - self.car_lat, 0.0, 5.0)
        s.seed_car(pos=pos, fwd=self.car_fwd, right=self.car_right,
                   node=0, t=0.5, entry=entry, car_len=self.car_len,
                   car_wid=self.car_wid)
        s.wv(ea.RC + 0x1AF0, tuple(self.road_fwd) + (0.0,))
        s.wv(ea.RC + 0x1B00, tuple(self.road_right) + (0.0,))
        fr = s.build_frame()
        bd = s.build_band()
        s.clear_profile()
        for lo, hi, kind, t, d in self.paints:
            s.paint_strips(lo, hi, kind, t, d)
        s.wf(ea.AI + 0x1D0, self.ceiling)
        s.wf(ea.AV + ea.AV_SPD_GATE, self.gate)
        s.wu(ea.RC + 0x1BF4, self.mode)
        s.wu(ea.RC + 0x1BF8, 1 if self.mode else 0)
        s.wu(ea.RC + 0x1BFC, 0)
        q = s.query(self.query)
        aim = s.aim_strip()
        timeq = [s.rb(ea.AV + ea.AV_TIME + i) for i in range(256)]
        distq = [s.rs(ea.AV + ea.AV_DIST + i * 2) for i in range(256)]
        typeq = [s.rb(ea.AV + ea.AV_TYPE + i) for i in range(256)]
        s.call(F_CHOOSE, {UC_X86_REG_ESI: ea.AV})
        fault = s.fault
        out = dict(fr)
        out.update(bd)
        out.update(q_mean=q[0], q_total=q[1], q_max=q[2], aimstrip=aim,
                   timeq=timeq, distq=distq, typeq=typeq,
                   state=s.rb(ea.AV + ea.AV_STATE),
                   speed=s.rf(ea.AV + ea.AV_SPEED),
                   rmean_r=s.rf(ea.AV + 0x490), rmean_l=s.rf(ea.AV + 0x494),
                   rtot_r=s.rf(ea.AV + 0x498), rtot_l=s.rf(ea.AV + 0x49C),
                   fault=fault)
        return out

    # --- port ---------------------------------------------------------
    def port(self):
        w = self.width
        args = [
            "left=%f,%f,%f" % (-w * 0.5, 0.0, 5.0),
            "right=%f,%f,%f" % (w * 0.5, 0.0, 5.0),
            "car=%f,%f,%f" % (w * 0.5 - self.car_lat, 0.0, 5.0),
            "rfwd=%f,%f,%f" % tuple(self.road_fwd),
            "rright=%f,%f,%f" % tuple(self.road_right),
            "cfwd=%f,%f,%f" % tuple(self.car_fwd),
            "len=%f" % self.car_len, "wid=%f" % self.car_wid,
            "gate=%f" % self.gate, "ceiling=%f" % self.ceiling,
            "mode=%d" % self.mode, "query=%d" % self.query,
            "frame=1", "band=1",
        ]
        for lo, hi, kind, t, d in self.paints:
            args.append("paints=%d:%d:%d:%f:%f" % (lo, hi, kind, t, d))
        args.append("choose=1")
        return run_probe(args)


def compare(c):
    r = c.retail()
    if r.get('fault'):
        FAILS.append("%-46s %-12s retail FAULT %s" % (c.name, '-', r['fault']))
        return
    p = c.port()
    chk(c.name, "width", float(p['width']), r['width'])
    chk(c.name, "lat_left", float(p['lat_left']), r['lat_left'])
    chk(c.name, "lat_right", float(p['lat_right']), r['lat_right'])
    pax = [float(x) for x in p['axis'].split(',')]
    for i, nm in enumerate("xyz"):
        chk(c.name, "axis." + nm, pax[i], r['axis'][i])
    chk(c.name, "lo", int(p['lo']), r['lo'])
    chk(c.name, "hi", int(p['hi']), r['hi'])
    chk(c.name, "win", int(p['win']), r['win'])
    for nm, key in (("time[]", 'timeq'), ("dist[]", 'distq'),
                    ("type[]", 'typeq')):
        pv = [int(x) for x in p[key.replace('q', 'q')].split(',')]
        if pv != r[key]:
            bad = [i for i in range(256) if pv[i] != r[key][i]]
            NCASE[0] += 1
            FAILS.append("%-46s %-12s %d strips differ, first %d: got %s want %s"
                         % (c.name, nm, len(bad), bad[0], pv[bad[0]],
                            r[key][bad[0]]))
        else:
            NCASE[0] += 1
    chk(c.name, "q_mean", float(p['q_mean']), r['q_mean'])
    chk(c.name, "q_total", float(p['q_total']), r['q_total'])
    chk(c.name, "q_max", float(p['q_max']), r['q_max'])
    chk(c.name, "aimstrip", int(p['aimstrip']), r['aimstrip'])
    chk(c.name, "state", int(p['state']), r['state'])
    chk(c.name, "speed", float(p['speed']), r['speed'])
    chk(c.name, "rmean_r", float(p['rmean_r']), r['rmean_r'])
    chk(c.name, "rmean_l", float(p['rmean_l']), r['rmean_l'])
    chk(c.name, "rtot_r", float(p['rtot_r']), r['rtot_r'])
    chk(c.name, "rtot_l", float(p['rtot_l']), r['rtot_l'])


def cases():
    out = []
    # --- frame / band geometry ---------------------------------------
    for w in (8.0, 12.0, 16.0, 24.0, 40.0):
        for lat in (1.0, 4.0, 8.0):
            if lat >= w:
                continue
            out.append(Case("frame w=%g lat=%g" % (w, lat),
                            width=w, car_lat=lat))
    # a car at an angle: the footprint band widens
    import math
    for deg in (0, 10, 30, 45, 60, 90):
        a = math.radians(deg)
        out.append(Case("band yaw=%ddeg" % deg, width=16.0, car_lat=8.0,
                        car_fwd=(math.sin(a), 0.0, math.cos(a))))
    for ln, wd in ((3.5, 1.7), (4.5, 2.0), (5.5, 2.4), (8.0, 2.6)):
        out.append(Case("band size %gx%g" % (ln, wd), width=16.0,
                        car_lat=8.0, car_len=ln, car_wid=wd))
    # The two extent fields are NOT interchangeable, and both this suite's
    # seeder and the port's caller used to have them swapped -- consistently,
    # so nothing here noticed.  Aligned to the road only racecar+0x2444 (the
    # WIDTH) moves the band; at 90 degrees only +0x2448 (the LENGTH) does.
    # Extreme asymmetry at both angles makes a one-sided swap impossible to
    # miss (223 checks fail if either side is put back).
    for deg in (0, 90):
        a = math.radians(deg)
        for ln, wd in ((12.0, 2.0), (4.5, 12.0)):
            out.append(Case("band extent %gx%g @%ddeg" % (ln, wd, deg),
                            width=16.0, car_lat=8.0, car_len=ln, car_wid=wd,
                            car_fwd=(math.sin(a), 0.0, math.cos(a))))

    # --- the world -> strip map and the stamp -------------------------
    out.append(Case("empty profile", width=16.0, car_lat=8.0))
    out.append(Case("traffic dead ahead 25 m",
                    paints=((103, 183, 3, 1.0, 25.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("traffic dead ahead 5 m",
                    paints=((103, 183, 3, 0.4, 5.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("traffic dead ahead 15 m",
                    paints=((103, 183, 3, 0.8, 15.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("traffic dead ahead 45 m",
                    paints=((103, 183, 3, 2.2, 45.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("traffic dead ahead 200 m",
                    paints=((103, 183, 3, 6.0, 200.0),), width=16.0,
                    car_lat=8.0))
    # a narrow occupier only on one side -> the chooser must pick a side
    out.append(Case("occupier on the LOW side",
                    paints=((103, 130, 3, 0.9, 20.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("occupier on the HIGH side",
                    paints=((126, 183, 3, 0.9, 20.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("occupier straddling the car",
                    paints=((120, 136, 3, 0.5, 8.0),), width=16.0,
                    car_lat=8.0))
    # a rival alongside (occupies strips but far in range)
    out.append(Case("rival alongside HIGH",
                    paints=((140, 156, 6, 1.5, 60.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("rival alongside, gate 60 drops type 6",
                    paints=((120, 140, 6, 1.5, 8.0),), width=16.0,
                    car_lat=8.0, gate=60.0))
    out.append(Case("rival alongside, gate 30 keeps type 6",
                    paints=((120, 140, 6, 1.5, 8.0),), width=16.0,
                    car_lat=8.0, gate=30.0))
    # walls / hard no-go
    out.append(Case("hard no-go across the road",
                    paints=((103, 183, 7, 0.0, 200.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("hard no-go on the HIGH side",
                    paints=((150, 183, 7, 0.0, 200.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("soft no-go type1 far",
                    paints=((103, 183, 1, 2.5, 101.0),), width=16.0,
                    car_lat=8.0))
    out.append(Case("soft no-go type2 + traffic",
                    paints=((103, 183, 2, 2.5, 101.0),
                            (120, 140, 3, 0.7, 12.0)), width=16.0,
                    car_lat=8.0))
    # layered stamps: type follows time, dist independent
    out.append(Case("layered stamps",
                    paints=((100, 180, 3, 2.0, 50.0),
                            (110, 170, 6, 3.0, 10.0),
                            (115, 165, 7, 1.0, 99.0)), width=16.0,
                    car_lat=8.0))
    # the query at several strips
    for q in (60, 100, 116, 128, 140, 183, 220):
        out.append(Case("query at strip %d" % q,
                        paints=((103, 183, 3, 1.0, 25.0),), width=16.0,
                        car_lat=8.0, query=q))
    # corner variants: the road mode gate
    for mode in (0, 2, 4):
        out.append(Case("mode=%d two-sided" % mode,
                        paints=((103, 130, 3, 0.9, 20.0),
                                (160, 183, 3, 1.1, 30.0)), width=16.0,
                        car_lat=8.0, mode=mode))
    # off-centre cars on a wide road
    for lat in (2.0, 6.0, 12.0, 20.0):
        out.append(Case("wide road lat=%g" % lat, width=26.0, car_lat=lat,
                        paints=((110, 150, 3, 1.2, 22.0),)))
    # ceilings
    for ceil in (20.0, 45.0, 88.0):
        out.append(Case("ceiling %g clear" % ceil, width=16.0, car_lat=8.0,
                        ceiling=ceil))
        out.append(Case("ceiling %g w/ traffic" % ceil, width=16.0,
                        car_lat=8.0, ceiling=ceil,
                        paints=((103, 183, 3, 3.5, 60.0),)))
    return out


def main():
    build_probe()
    cs = cases()
    for c in cs:
        compare(c)
    print("validate_ai_avoid: %d checks over %d cases" % (NCASE[0], len(cs)))
    if FAILS:
        print("FAILURES (%d):" % len(FAILS))
        for f in FAILS[:60]:
            print("  " + f)
        if len(FAILS) > 60:
            print("  ... %d more" % (len(FAILS) - 60))
        return 1
    print("all green")
    return 0


if __name__ == '__main__':
    sys.exit(main())
