// RUNTIME VEHICLE ROSTER.
//
// Replaces the compiled-in src/burnout3_vehicle_data.h, the 107-entry VEHICLES
// table tools/extract_vehicles.py generated by walking the user's pveh/
// directory.  Every consumer name below keeps its old spelling -- VEHICLES,
// VEHICLE_COUNT, VehicleInfo, VEH_PLAYER, VEH_TRAFFIC -- so call sites are
// unchanged; only the STORAGE moves, from a const array chosen at compile time
// to a table filled on first use from
//
//     build/cars/roster.bin                      ('B3VR', version 1)
//
// which tools/cextract's `vehicle_roster` stage writes alongside the header it
// still generates (tools/cextract/cx_cars_roster.c, and the format block in
// tools/cextract/cx_extract.h).
//
// ============================================================ PROVENANCE [C]
// Unchanged from the header.  Every row is one pveh/<CLASS>/Car<n>.bgv|btv
// file's own header, with only fields verified against the files emitted:
//
//     +0x00 u32 magic 0x17            holds for all 107
//     +0x08 u32 self-describing size  cross-checked against the file on disc;
//                                     a mismatch rejects the file outright
//     +0x0C u32 variant/feature word  0x0406 / 0x0405 / 0x0403 / 0 (traffic)
//     +0x10 u32 section count
//     +0x14 f32 dim_a  +0x18 f32 dim_b
//
// and the row ORDER is the extractor's: class by class, and within a class the
// .bgv (player) pass entirely before the .btv (traffic) pass, each sorted by
// tools/extract_vehicles.py's car_sort_key().  The port indexes the roster by
// position in several places (roster_player_car's nth, the car-select ros[]
// list), so that order is part of the contract and roster.bin preserves it.
//
// VLIST_VERSION / VLIST_DECLARED_COUNT come from pveh/vlist.bin's own header
// (+0x00 version, +0x04 declared count) and are carried for the cross-check.
//
// ================================================================= PRECISION
// dim_a/dim_b were printed "%.5ff" by the header, so the compiled constants
// were the ROUNDED decimals and not the raw f32 out of the file.  The
// extractor reproduces that rounding before storing the f32, which makes this
// table bit-identical to the one it replaces rather than merely close to it;
// the full-precision values are one format change away in cx_cars_roster.c.
//
// ===================================================================== LOUD
// A missing roster.bin does not look missing: the port would simply find no
// cars and draw an empty grid.  The loader names the file and stops.

#ifndef BURNOUT3_VEHICLE_DATA_RUNTIME_H
#define BURNOUT3_VEHICLE_DATA_RUNTIME_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Format cap, not a fleet count: retail ships 107.  The loader refuses a file
 * that claims more rather than truncating silently.  Used as an array bound
 * where the old VEHICLE_COUNT was (it was a #define, and is now a call). */
#define B3_VEHICLE_MAX 256

typedef enum { VEH_PLAYER = 0, VEH_TRAFFIC = 1 } VehicleKind;

typedef struct {
    const char*  file;      // source filename in pveh/<class>/
    const char*  class_code;
    const char*  class_name;
    VehicleKind  kind;
    unsigned     data_size; // bytes of model data on disk
    unsigned     variant;   // header +0x0C feature word
    unsigned     sections;  // header +0x10
    float        dim_a;     // header +0x14
    float        dim_b;     // header +0x18
} VehicleInfo;

static struct {
    int         loaded;
    int         count;
    unsigned    vlist_version;
    unsigned    vlist_declared;
    VehicleInfo v[B3_VEHICLE_MAX];
    char        file[B3_VEHICLE_MAX][16];
    char        cls[B3_VEHICLE_MAX][8];
    char        cname[B3_VEHICLE_MAX][16];
} g_vroster;

static inline unsigned b3_vr_u32(const unsigned char* d) {
    return (unsigned)d[0] | ((unsigned)d[1] << 8) | ((unsigned)d[2] << 16)
         | ((unsigned)d[3] << 24);
}

static inline void b3_vehicle_roster_fatal(const char* path, const char* why) {
    fprintf(stderr,
        "[Burnout3] FATAL: %s -- %s.\n"
        "  This is the pveh/ vehicle roster; there is no compiled-in copy to\n"
        "  fall back to, and without it there are no cars at all.\n"
        "  Extract it from your own dump:  tools/cextract/build.sh && "
        "cxtract --all-global --out .\n"
        "  (or just this stage:  cxtract --only vehicle_roster --out .)\n",
        path, why);
    exit(2);
}

/* build/cars/roster.bin, 'B3VR' version 1 (tools/cextract/cx_cars_roster.c):
 *   +0x00 char[4] 'B3VR'      +0x04 u32 version = 1
 *   +0x08 u32 count           +0x0C u32 stride = 64
 *   +0x10 u32 vlist_version   +0x14 u32 vlist_declared_count
 *   +0x18 count x 64-byte record {char[16] file, char[8] class_code,
 *          char[16] class_name, u32 kind, u32 data_size, u32 variant,
 *          u32 sections, f32 dim_a, f32 dim_b}
 * Loads once; FATAL rather than substituting anything. */
static inline int b3_vehicle_roster_load(void) {
    const char* path = getenv("B3_ROSTER_BIN");
    unsigned char hdr[24];
    unsigned n, stride, i;
    FILE* f;

    if (g_vroster.loaded) return g_vroster.count;
    if (!path || !*path) path = "build/cars/roster.bin";
    g_vroster.loaded = 1;

    f = fopen(path, "rb");
    if (!f) b3_vehicle_roster_fatal(path, "no such file");
    if (fread(hdr, 1, 24, f) != 24 || memcmp(hdr, "B3VR", 4) != 0
        || b3_vr_u32(hdr + 4) != 1u) {
        fclose(f);
        b3_vehicle_roster_fatal(path, "not a B3VR version 1 asset");
    }
    n      = b3_vr_u32(hdr + 8);
    stride = b3_vr_u32(hdr + 12);
    if (n == 0 || n > B3_VEHICLE_MAX || stride != 64) {
        fclose(f);
        b3_vehicle_roster_fatal(path, "count or record stride outside the "
                                      "format cap");
    }
    g_vroster.vlist_version  = b3_vr_u32(hdr + 16);
    g_vroster.vlist_declared = b3_vr_u32(hdr + 20);

    for (i = 0; i < n; i++) {
        unsigned char rec[64];
        unsigned bits;
        float a, b;
        if (fread(rec, 1, 64, f) != 64) {
            fclose(f);
            b3_vehicle_roster_fatal(path, "truncated in the vehicle table");
        }
        memcpy(g_vroster.file[i],  rec,      16);
        memcpy(g_vroster.cls[i],   rec + 16,  8);
        memcpy(g_vroster.cname[i], rec + 24, 16);
        g_vroster.file[i][15]  = '\0';   /* never trust a file to terminate */
        g_vroster.cls[i][7]    = '\0';
        g_vroster.cname[i][15] = '\0';
        bits = b3_vr_u32(rec + 56); memcpy(&a, &bits, 4);
        bits = b3_vr_u32(rec + 60); memcpy(&b, &bits, 4);
        g_vroster.v[i].file       = g_vroster.file[i];
        g_vroster.v[i].class_code = g_vroster.cls[i];
        g_vroster.v[i].class_name = g_vroster.cname[i];
        g_vroster.v[i].kind       = b3_vr_u32(rec + 40) ? VEH_TRAFFIC
                                                        : VEH_PLAYER;
        g_vroster.v[i].data_size  = b3_vr_u32(rec + 44);
        g_vroster.v[i].variant    = b3_vr_u32(rec + 48);
        g_vroster.v[i].sections   = b3_vr_u32(rec + 52);
        g_vroster.v[i].dim_a      = a;
        g_vroster.v[i].dim_b      = b;
    }
    fclose(f);
    g_vroster.count = (int)n;
    /* stderr: see the note in burnout3_car_physics_runtime.h */
    fprintf(stderr, "[Burnout3] vehicle roster: %d vehicles from %s "
            "(vlist v%u, declares %u)\n", g_vroster.count, path,
            g_vroster.vlist_version, g_vroster.vlist_declared);
    return g_vroster.count;
}

static inline const VehicleInfo* b3_vehicle_roster(void) {
    b3_vehicle_roster_load();
    return g_vroster.v;
}

static inline int b3_vehicle_count(void) {
    return b3_vehicle_roster_load();
}

/* The old spellings, now resolving to runtime storage.  VEHICLE_COUNT was
 * used as an ARRAY BOUND in two places in src/burnout3_full.c; those now use
 * B3_VEHICLE_MAX, which is the format cap and a real constant. */
#define VEHICLES        (b3_vehicle_roster())
#define VEHICLE_COUNT   (b3_vehicle_count())

/* pveh/vlist.bin's own header, kept for the cross-check the header carried as
 * two #defines.  0/0 when the dump has no vlist.bin. */
#define VLIST_VERSION        (b3_vehicle_roster_load(), g_vroster.vlist_version)
#define VLIST_DECLARED_COUNT (b3_vehicle_roster_load(), g_vroster.vlist_declared)

#endif /* BURNOUT3_VEHICLE_DATA_RUNTIME_H */
