// GENERATED by tools/gen_score_ranges.py -- do not edit by hand.
//
// The recovered byte ranges of B3ScoreEvents, at retail's score offsets.
// Built from the parity assertions so it cannot drift from the struct.
#ifndef BURNOUT3_SCORE_RANGES_H
#define BURNOUT3_SCORE_RANGES_H

#include <stddef.h>
#include "burnout3_score_events.h"

typedef struct { unsigned off, len; } B3ScoreRange;
#define B3_SCORE_LEN(f) ((unsigned)sizeof(((B3ScoreEvents*)0)->f))

static const B3ScoreRange B3_SCORE_RANGES[] = {
    { (unsigned)offsetof(B3ScoreEvents, air), B3_SCORE_LEN(air) },
    { (unsigned)offsetof(B3ScoreEvents, onc), B3_SCORE_LEN(onc) },
    { (unsigned)offsetof(B3ScoreEvents, drift), B3_SCORE_LEN(drift) },
    { (unsigned)offsetof(B3ScoreEvents, air_scored), B3_SCORE_LEN(air_scored) },
    { (unsigned)offsetof(B3ScoreEvents, onc_scored), B3_SCORE_LEN(onc_scored) },
    { (unsigned)offsetof(B3ScoreEvents, drift_scored), B3_SCORE_LEN(drift_scored) },
    { (unsigned)offsetof(B3ScoreEvents, nm_total), B3_SCORE_LEN(nm_total) },
    { (unsigned)offsetof(B3ScoreEvents, nm_chain), B3_SCORE_LEN(nm_chain) },
    { (unsigned)offsetof(B3ScoreEvents, prev_clock), B3_SCORE_LEN(prev_clock) },
    { (unsigned)offsetof(B3ScoreEvents, nm_last), B3_SCORE_LEN(nm_last) },
    { (unsigned)offsetof(B3ScoreEvents, nm_chain_end), B3_SCORE_LEN(nm_chain_end) },
    { (unsigned)offsetof(B3ScoreEvents, nm_id), B3_SCORE_LEN(nm_id) },
    { (unsigned)offsetof(B3ScoreEvents, nm_seen), B3_SCORE_LEN(nm_seen) },
    { (unsigned)offsetof(B3ScoreEvents, nm_armed), B3_SCORE_LEN(nm_armed) },
    { (unsigned)offsetof(B3ScoreEvents, nm), B3_SCORE_LEN(nm) },
    { (unsigned)offsetof(B3ScoreEvents, rub_last), B3_SCORE_LEN(rub_last) },
    { (unsigned)offsetof(B3ScoreEvents, rub_time), B3_SCORE_LEN(rub_time) },
    { (unsigned)offsetof(B3ScoreEvents, rub_start), B3_SCORE_LEN(rub_start) },
    { (unsigned)offsetof(B3ScoreEvents, rub_prev_touch), B3_SCORE_LEN(rub_prev_touch) },
    { (unsigned)offsetof(B3ScoreEvents, rub_touch), B3_SCORE_LEN(rub_touch) },
    { (unsigned)offsetof(B3ScoreEvents, rub), B3_SCORE_LEN(rub) },
    { (unsigned)offsetof(B3ScoreEvents, rub_target), B3_SCORE_LEN(rub_target) },
};

#define B3_SCORE_RANGE_COUNT (sizeof(B3_SCORE_RANGES)/sizeof(B3_SCORE_RANGES[0]))

#endif // BURNOUT3_SCORE_RANGES_H
