// GENERATED by tools/gen_tdcar_ranges.py -- do not edit by hand.
// (the slam-scorer ranges were added by hand with the generator missing;
//  every one is covered by a _Static_assert in burnout3_td_rules.h)
//
// The recovered byte ranges of B3TdCar, at retail's racecar offsets.
// Built from the parity assertions so it cannot drift from the struct.
//
// td_rules is STATEFUL, unlike the stateless car-vs-car resolve: the
// emulated world owns per-car score state between calls, so these ranges
// carry the port's cars into it at the SAME offsets, nothing converted.
#ifndef BURNOUT3_TDCAR_RANGES_H
#define BURNOUT3_TDCAR_RANGES_H

#include <stddef.h>
#include "burnout3_td_rules.h"

typedef struct { unsigned off, len; } B3TdCarRange;
#define B3_TDCAR_LEN(f) ((unsigned)sizeof(((B3TdCar*)0)->f))

static const B3TdCarRange B3_TDCAR_RANGES[] = {
    { (unsigned)offsetof(B3TdCar, speed_ms), B3_TDCAR_LEN(speed_ms) },
    { (unsigned)offsetof(B3TdCar, dbl_window), B3_TDCAR_LEN(dbl_window) },
    { (unsigned)offsetof(B3TdCar, dbl_count), B3_TDCAR_LEN(dbl_count) },
    { (unsigned)offsetof(B3TdCar, spree_window), B3_TDCAR_LEN(spree_window) },
    { (unsigned)offsetof(B3TdCar, spree_count), B3_TDCAR_LEN(spree_count) },
    { (unsigned)offsetof(B3TdCar, aftertouch_count), B3_TDCAR_LEN(aftertouch_count) },
    { (unsigned)offsetof(B3TdCar, bp), B3_TDCAR_LEN(bp) },
    { (unsigned)offsetof(B3TdCar, slams_made), B3_TDCAR_LEN(slams_made) },
    { (unsigned)offsetof(B3TdCar, aftertouch_td), B3_TDCAR_LEN(aftertouch_td) },
    { (unsigned)offsetof(B3TdCar, td_made), B3_TDCAR_LEN(td_made) },
    { (unsigned)offsetof(B3TdCar, race_state), B3_TDCAR_LEN(race_state) },
    { (unsigned)offsetof(B3TdCar, crash_time), B3_TDCAR_LEN(crash_time) },
    { (unsigned)offsetof(B3TdCar, last_slam_time), B3_TDCAR_LEN(last_slam_time) },
    { (unsigned)offsetof(B3TdCar, times_slammed), B3_TDCAR_LEN(times_slammed) },
    { (unsigned)offsetof(B3TdCar, slam_time), B3_TDCAR_LEN(slam_time) },
    { (unsigned)offsetof(B3TdCar, slam_type), B3_TDCAR_LEN(slam_type) },
    { (unsigned)offsetof(B3TdCar, last_victim), B3_TDCAR_LEN(last_victim) },
    { (unsigned)offsetof(B3TdCar, claim), B3_TDCAR_LEN(claim) },
    { (unsigned)offsetof(B3TdCar, claim_aftertouch), B3_TDCAR_LEN(claim_aftertouch) },
    { (unsigned)offsetof(B3TdCar, claim_psyche), B3_TDCAR_LEN(claim_psyche) },
    { (unsigned)offsetof(B3TdCar, td_credited), B3_TDCAR_LEN(td_credited) },
    { (unsigned)offsetof(B3TdCar, td_by), B3_TDCAR_LEN(td_by) },
    { (unsigned)offsetof(B3TdCar, psyche_target), B3_TDCAR_LEN(psyche_target) },
    { (unsigned)offsetof(B3TdCar, psyche_armed), B3_TDCAR_LEN(psyche_armed) },
    { (unsigned)offsetof(B3TdCar, taken_down_by), B3_TDCAR_LEN(taken_down_by) },
    { (unsigned)offsetof(B3TdCar, revenge_flag), B3_TDCAR_LEN(revenge_flag) },
    { (unsigned)offsetof(B3TdCar, shunt_victim_time), B3_TDCAR_LEN(shunt_victim_time) },
    { (unsigned)offsetof(B3TdCar, aggressor), B3_TDCAR_LEN(aggressor) },
    { (unsigned)offsetof(B3TdCar, aggressor_time), B3_TDCAR_LEN(aggressor_time) },
    { (unsigned)offsetof(B3TdCar, crashed), B3_TDCAR_LEN(crashed) },
    { (unsigned)offsetof(B3TdCar, cls), B3_TDCAR_LEN(cls) },
    { (unsigned)offsetof(B3TdCar, grid), B3_TDCAR_LEN(grid) },
    { (unsigned)offsetof(B3TdCar, recover_at), B3_TDCAR_LEN(recover_at) },
    { (unsigned)offsetof(B3TdCar, bp_takedown), B3_TDCAR_LEN(bp_takedown) },
    { (unsigned)offsetof(B3TdCar, bp_aggressive), B3_TDCAR_LEN(bp_aggressive) },
    { (unsigned)offsetof(B3TdCar, boost_tier), B3_TDCAR_LEN(boost_tier) },
    { (unsigned)offsetof(B3TdCar, boost_size), B3_TDCAR_LEN(boost_size) },
    { (unsigned)offsetof(B3TdCar, boost_meter), B3_TDCAR_LEN(boost_meter) },
    { (unsigned)offsetof(B3TdCar, boost_earned), B3_TDCAR_LEN(boost_earned) },
    { (unsigned)offsetof(B3TdCar, boost_mult), B3_TDCAR_LEN(boost_mult) },
    { (unsigned)offsetof(B3TdCar, boost_bonus), B3_TDCAR_LEN(boost_bonus) },
    { (unsigned)offsetof(B3TdCar, boost_peg_a), B3_TDCAR_LEN(boost_peg_a) },
    { (unsigned)offsetof(B3TdCar, boost_peg_b), B3_TDCAR_LEN(boost_peg_b) },
    { (unsigned)offsetof(B3TdCar, boosting), B3_TDCAR_LEN(boosting) },
    { (unsigned)offsetof(B3TdCar, boost_forcestop), B3_TDCAR_LEN(boost_forcestop) },
    { (unsigned)offsetof(B3TdCar, boost_ramp_done), B3_TDCAR_LEN(boost_ramp_done) },
    { (unsigned)offsetof(B3TdCar, slam_kind), B3_TDCAR_LEN(slam_kind) },
    { (unsigned)offsetof(B3TdCar, slam_cheap), B3_TDCAR_LEN(slam_cheap) },
    { (unsigned)offsetof(B3TdCar, slam_burning), B3_TDCAR_LEN(slam_burning) },
    { (unsigned)offsetof(B3TdCar, crash_stamp), B3_TDCAR_LEN(crash_stamp) },
    { (unsigned)offsetof(B3TdCar, slam_energy), B3_TDCAR_LEN(slam_energy) },
    { (unsigned)offsetof(B3TdCar, slammed_energy), B3_TDCAR_LEN(slammed_energy) },
    { (unsigned)offsetof(B3TdCar, last_slam_kind), B3_TDCAR_LEN(last_slam_kind) },
    { (unsigned)offsetof(B3TdCar, td_credited_fx), B3_TDCAR_LEN(td_credited_fx) },
    { (unsigned)offsetof(B3TdCar, respawning), B3_TDCAR_LEN(respawning) },
    { (unsigned)offsetof(B3TdCar, human_slam), B3_TDCAR_LEN(human_slam) },
    { (unsigned)offsetof(B3TdCar, ai_aggression), B3_TDCAR_LEN(ai_aggression) },
    { (unsigned)offsetof(B3TdCar, ai_aggr_step), B3_TDCAR_LEN(ai_aggr_step) },
    { (unsigned)offsetof(B3TdCar, ai_aggr_cap), B3_TDCAR_LEN(ai_aggr_cap) },
};

#define B3_TDCAR_RANGE_COUNT (sizeof(B3_TDCAR_RANGES) / sizeof(B3_TDCAR_RANGES[0]))

#endif // BURNOUT3_TDCAR_RANGES_H
