// GENERATED by tools/gen_crash_ranges.py -- do not edit by hand.
//
// The vehicle fields FUN_0011AEF0 (chassis-vs-world resolve) touches.
// Each range is written at the SAME offset on both sides; nothing is
// converted, and the rest of retail's vehicle stays as the emulator
// seeded it -- including the veh+0x200 soup the resolve reads.
#ifndef BURNOUT3_CRASH_RANGES_H
#define BURNOUT3_CRASH_RANGES_H

#include <stddef.h>
#include "burnout3_vehicle_sim.h"

typedef struct { unsigned off, len; } B3CrashRange;

#define B3_CRASHVEH_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))
static const B3CrashRange B3_CRASHVEH_RANGES[] = {
    { (unsigned)offsetof(B3VehicleFull, rb.inv_inertia_world), B3_CRASHVEH_LEN(rb.inv_inertia_world) },  // +0x0040
    { (unsigned)offsetof(B3VehicleFull, rb.inv_frame), B3_CRASHVEH_LEN(rb.inv_frame) },  // +0x0070
    { (unsigned)offsetof(B3VehicleFull, rb.vel), B3_CRASHVEH_LEN(rb.vel) },  // +0x00B0
    { (unsigned)offsetof(B3VehicleFull, rb.dir), B3_CRASHVEH_LEN(rb.dir) },  // +0x00C0
    { (unsigned)offsetof(B3VehicleFull, rb.omega), B3_CRASHVEH_LEN(rb.omega) },  // +0x00D0
    { (unsigned)offsetof(B3VehicleFull, rb.force_acc), B3_CRASHVEH_LEN(rb.force_acc) },  // +0x00F0
    { (unsigned)offsetof(B3VehicleFull, rb.imp_force), B3_CRASHVEH_LEN(rb.imp_force) },  // +0x0110
    { (unsigned)offsetof(B3VehicleFull, rb.imp_torque), B3_CRASHVEH_LEN(rb.imp_torque) },  // +0x0120
    { (unsigned)offsetof(B3VehicleFull, rb.deflection), B3_CRASHVEH_LEN(rb.deflection) },  // +0x0130
    { (unsigned)offsetof(B3VehicleFull, contact_pt_160), B3_CRASHVEH_LEN(contact_pt_160) },  // +0x0160
    { (unsigned)offsetof(B3VehicleFull, contact_n_170), B3_CRASHVEH_LEN(contact_n_170) },  // +0x0170
    { (unsigned)offsetof(B3VehicleFull, surface_190), B3_CRASHVEH_LEN(surface_190) },  // +0x0190
    { (unsigned)offsetof(B3VehicleFull, impact_194), B3_CRASHVEH_LEN(impact_194) },  // +0x0194
    { (unsigned)offsetof(B3VehicleFull, contact_state_198), B3_CRASHVEH_LEN(contact_state_198) },  // +0x0198
    { (unsigned)offsetof(B3VehicleFull, half_ext), B3_CRASHVEH_LEN(half_ext) },  // +0x01D0
    { (unsigned)offsetof(B3VehicleFull, center_off), B3_CRASHVEH_LEN(center_off) },  // +0x01E0
    { (unsigned)offsetof(B3VehicleFull, mass), B3_CRASHVEH_LEN(mass) },  // +0x01F0
    { (unsigned)offsetof(B3VehicleFull, asleep_020E), B3_CRASHVEH_LEN(asleep_020E) },  // +0x020E
    { (unsigned)offsetof(B3VehicleFull, flags_1353), B3_CRASHVEH_LEN(flags_1353) },  // +0x1353
    { (unsigned)offsetof(B3VehicleFull, surface_grip_13A8), B3_CRASHVEH_LEN(surface_grip_13A8) },  // +0x13A8
    { (unsigned)offsetof(B3VehicleFull, brake_1404), B3_CRASHVEH_LEN(brake_1404) },  // +0x1404
    { (unsigned)offsetof(B3VehicleFull, drift_dir_1434), B3_CRASHVEH_LEN(drift_dir_1434) },  // +0x1434
    { (unsigned)offsetof(B3VehicleFull, trans.gear), B3_CRASHVEH_LEN(trans.gear) },  // +0x14C8
    { (unsigned)offsetof(B3VehicleFull, drift_state_1524), B3_CRASHVEH_LEN(drift_state_1524) },  // +0x1524
    { (unsigned)offsetof(B3VehicleFull, authority_1534), B3_CRASHVEH_LEN(authority_1534) },  // +0x1534
    { (unsigned)offsetof(B3VehicleFull, no_scrub_153E), B3_CRASHVEH_LEN(no_scrub_153E) },  // +0x153E
};
#define B3_CRASHVEH_RANGES_COUNT (sizeof(B3_CRASHVEH_RANGES)/sizeof(B3_CRASHVEH_RANGES[0]))

#endif // BURNOUT3_CRASH_RANGES_H
