// GENERATED by tools/gen_sfx_emitters.py -- do not edit by hand.
//
// The retail emitter behind each B3SfxEvent, with the calling
// convention it needs. Address 0 = not switchable: no captured
// convention for that emitter, so b3_sfx_event stays on the port.
#ifndef BURNOUT3_SFX_EMITTERS_H
#define BURNOUT3_SFX_EMITTERS_H

#include "burnout3_sfx.h"

typedef struct { unsigned addr; int kind; const char* wave; } B3SfxEmitter;

// kind ids match tools/emulate_sfx.py's `fire(kind=...)` strings:
//   0 = ecx
//   1 = eax_x0
//   2 = eax_m8
//   3 = st_obj_m8
//   4 = st4
static const B3SfxEmitter B3_SFX_EMITTERS[] = {
    { 0x0014F3E0, 0, "IMPACTNUDG" },  // B3_SFX_IMPACT_NUDGE
    { 0x0014F690, 3, "IMPACTFATA" },  // B3_SFX_IMPACT_FATAL
    { 0x0014F130, 2, "IMPACTFATA" },  // B3_SFX_IMPACT_FATAL_CM
    { 0x0014EEA0, 0, "IMPACTWORL" },  // B3_SFX_IMPACT_WORLD
    { 0x0014D5F0, 2, "GLASSFRONT" },  // B3_SFX_GLASS_FRONT
    { 0x0014D8A0, 2, "GLASSSIDES" },  // B3_SFX_GLASS_SIDES
    { 0x0014DB50, 2, "GLASSWINDS" },  // B3_SFX_GLASS_WINDS
    { 0x0014EB00, 1, "CARPARTLDE" },  // B3_SFX_PANEL_L_DEFORM
    { 0x0014ECB0, 1, "CARPARTMDE" },  // B3_SFX_PANEL_M_DEFORM
    { 0x0014FC80, 1, "CARPARTLRE" },  // B3_SFX_PANEL_L_REMOVE
    { 0x0014FE60, 1, "CARPARTMRE" },  // B3_SFX_PANEL_M_REMOVE
    { 0x00150040, 1, "CARPARTLPR" },  // B3_SFX_PANEL_L_PROP
    { 0x00150260, 1, "CARPARTMPR" },  // B3_SFX_PANEL_M_PROP
    { 0x00150480, 1, "CARPARTWPR" },  // B3_SFX_PANEL_W_PROP
    { 0x0, -1, 0 },  // B3_SFX_SLAM
    { 0x0, -1, 0 },  // B3_SFX_SHUNT
    { 0x0, -1, 0 },  // B3_SFX_BOOST_GAIN
    { 0x0, -1, 0 },  // B3_SFX_BOOST_LOSS
    { 0x0, -1, 0 },  // B3_SFX_BOOST_LOOP
    { 0x0, -1, 0 },  // B3_SFX_BOOST_IN
    { 0x0, -1, 0 },  // B3_SFX_BOOST_OUT
    { 0x0, -1, 0 },  // B3_SFX_SCRAPE_LO
    { 0x0, -1, 0 },  // B3_SFX_SCRAPE_HI
    { 0x00150B90, 4, "KURBBOUNCE" },  // B3_SFX_KERB
    { 0x0, -1, 0 },  // B3_SFX_AIRRAM
    { 0x0, -1, 0 },  // B3_SFX_EXPLOSION
    { 0x0, -1, 0 },  // B3_SFX_FIRE
    { 0x0, -1, 0 },  // B3_SFX_STEAM
    { 0x0, -1, 0 },  // B3_SFX_CAR_ALARM
    { 0x0, -1, 0 },  // B3_SFX_NEAR_MISS
    { 0x0, -1, 0 },  // B3_SFX_TRAFFIC_PASS_BIG
    { 0x0, -1, 0 },  // B3_SFX_TRAFFIC_PASS_SMALL
    { 0x0, -1, 0 },  // B3_SFX_SURFACE_TAR
    { 0x0, -1, 0 },  // B3_SFX_SURFACE_GVL
    { 0x0, -1, 0 },  // B3_SFX_SURFACE_WOOD
    { 0x0, -1, 0 },  // B3_SFX_SURFACE_METAL
    { 0x0, -1, 0 },  // B3_SFX_SURFACE_SNOW
    { 0x0, -1, 0 },  // B3_SFX_SKID_1
    { 0x0, -1, 0 },  // B3_SFX_SKID_2
    { 0x0, -1, 0 },  // B3_SFX_SKID_3
    { 0x0, -1, 0 },  // B3_SFX_GEAR
};
#define B3_SFX_EMITTER_COUNT (sizeof(B3_SFX_EMITTERS)/sizeof(B3_SFX_EMITTERS[0]))

#endif // BURNOUT3_SFX_EMITTERS_H
