// GENERATED by tools/gen_retail_struct.py -- do not edit by hand.
//
// Burnout 3's live vehicle object, at RETAIL's own offsets.
//
// The point of this shape is that there is nothing to convert: the
// port's C and the game's x86 address the same bytes at the same
// places, so a feature can be switched between them without a
// marshalling layer in the middle. Every field carries a
// _Static_assert, so an offset that drifts fails the build rather
// than corrupting state at runtime.
//
// Harness-only state does NOT belong here. Retail code runs over
// this memory; anything invented squatting on bytes we have not
// identified would be trampled, or would trample. Keep GLUE in a
// parallel struct keyed by the same index.
#ifndef BURNOUT3_VEHICLE_RETAIL_H
#define BURNOUT3_VEHICLE_RETAIL_H

#include <stddef.h>

#define B3_VEHICLE_RETAIL_SPAN 0x1A00u

// PACKED deliberately. Retail's layout has no alignment we
// control -- the wheel count is a byte at +0x1169, and a 4-byte
// field at a non-4-aligned offset makes the compiler insert its
// own padding and shift everything after it. Explicit padding
// only holds if the compiler adds none of its own.
typedef struct __attribute__((packed)) B3VehicleRetail {
    unsigned char _pad00[0x14C];
    float          cfg_steer_max_14C;     // +0x014C
    unsigned char _pad01[0x4];
    float          cfg_steer_maxvel_154;  // +0x0154
    unsigned char _pad02[0x8];
    float          contact_pt_160[4];     // +0x0160
    float          contact_n_170[4];      // +0x0170
    unsigned char _pad03[0x10];
    float          cfg_steer_drag_190;    // +0x0190
    float          impact_194;            // +0x0194
    int            contact_state_198;     // +0x0198
    unsigned char _pad04[0x34];
    float          half_ext[4];           // +0x01D0
    float          center_off[4];         // +0x01E0
    float          mass;                  // +0x01F0
    float          com_height;            // +0x01F4
    unsigned char _pad05[0x19];
    unsigned char  landed_211;            // +0x0211
    unsigned char  contact_212;           // +0x0212
    unsigned char  contact_213;           // +0x0213
    unsigned char _pad06[0x1];
    unsigned char  class_215;             // +0x0215
    unsigned char _pad07[0x10E];
    float          grip_scalar;           // +0x0324
    unsigned char _pad08[0x174];
    float          ground_clear;          // +0x049C
    unsigned char _pad09[0xCC0];
    unsigned short surface_1160;          // +0x1160
    unsigned char _pad10[0x2];
    float          steer_deg_1164;        // +0x1164
    unsigned char _pad11[0x1];
    int            wheel_count;           // +0x1169
    unsigned char _pad12[0x1E3];
    float          launch_time_1350;      // +0x1350
    unsigned char _pad13[0x54];
    float          surface_grip_13A8;     // +0x13A8
    unsigned char _pad14[0x34];
    float          aggr_time_13E0;        // +0x13E0
    float          aggr_total_13E4;       // +0x13E4
    float          aggr_angle_13E8;       // +0x13E8
    float          aggr_vel_13EC;         // +0x13EC
    float          aggr_drag_13F0;        // +0x13F0
    float          ooc_slam_1598;         // +0x13F4
    unsigned char _pad15[0x4];
    unsigned char  input_bits_13FC;       // +0x13FC
    unsigned char _pad16[0x37];
    float          drift_dir_1434;        // +0x1434
    unsigned char _pad17[0xE8];
    float          drive_torque_1520;     // +0x1520
    int            drift_state_1524;      // +0x1524
    unsigned char _pad18[0x4];
    float          timer_152C;            // +0x152C
    unsigned char _pad19[0x4];
    float          authority_1534;        // +0x1534
    unsigned char _pad20[0x4];
    unsigned char  hit_side_153C;         // +0x153C
    unsigned char _pad21[0x1];
    unsigned char  no_scrub_153E;         // +0x153E
    unsigned char _pad22[0x8D];
    unsigned char  surf_bit15_15CC;       // +0x15CC
    unsigned char _pad23[0xC3];
    float          ooc_wall_1690;         // +0x1690
    unsigned char _pad24[0x28C];
    int            racecar_class_1920;    // +0x1920
    unsigned char _pad25[0xDC];
} B3VehicleRetail;

_Static_assert(sizeof(B3VehicleRetail) == B3_VEHICLE_RETAIL_SPAN,
               "vehicle span drifted");
_Static_assert(offsetof(B3VehicleRetail, cfg_steer_max_14C) == 0x014C,
               "cfg_steer_max_14C moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, cfg_steer_maxvel_154) == 0x0154,
               "cfg_steer_maxvel_154 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, contact_pt_160) == 0x0160,
               "contact_pt_160 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, contact_n_170) == 0x0170,
               "contact_n_170 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, cfg_steer_drag_190) == 0x0190,
               "cfg_steer_drag_190 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, impact_194) == 0x0194,
               "impact_194 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, contact_state_198) == 0x0198,
               "contact_state_198 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, half_ext) == 0x01D0,
               "half_ext moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, center_off) == 0x01E0,
               "center_off moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, mass) == 0x01F0,
               "mass moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, com_height) == 0x01F4,
               "com_height moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, landed_211) == 0x0211,
               "landed_211 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, contact_212) == 0x0212,
               "contact_212 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, contact_213) == 0x0213,
               "contact_213 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, class_215) == 0x0215,
               "class_215 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, grip_scalar) == 0x0324,
               "grip_scalar moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, ground_clear) == 0x049C,
               "ground_clear moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, surface_1160) == 0x1160,
               "surface_1160 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, steer_deg_1164) == 0x1164,
               "steer_deg_1164 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, wheel_count) == 0x1169,
               "wheel_count moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, launch_time_1350) == 0x1350,
               "launch_time_1350 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, surface_grip_13A8) == 0x13A8,
               "surface_grip_13A8 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, aggr_time_13E0) == 0x13E0,
               "aggr_time_13E0 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, aggr_total_13E4) == 0x13E4,
               "aggr_total_13E4 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, aggr_angle_13E8) == 0x13E8,
               "aggr_angle_13E8 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, aggr_vel_13EC) == 0x13EC,
               "aggr_vel_13EC moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, aggr_drag_13F0) == 0x13F0,
               "aggr_drag_13F0 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, ooc_slam_1598) == 0x13F4,
               "ooc_slam_1598 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, input_bits_13FC) == 0x13FC,
               "input_bits_13FC moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, drift_dir_1434) == 0x1434,
               "drift_dir_1434 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, drive_torque_1520) == 0x1520,
               "drive_torque_1520 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, drift_state_1524) == 0x1524,
               "drift_state_1524 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, timer_152C) == 0x152C,
               "timer_152C moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, authority_1534) == 0x1534,
               "authority_1534 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, hit_side_153C) == 0x153C,
               "hit_side_153C moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, no_scrub_153E) == 0x153E,
               "no_scrub_153E moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, surf_bit15_15CC) == 0x15CC,
               "surf_bit15_15CC moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, ooc_wall_1690) == 0x1690,
               "ooc_wall_1690 moved off retail's offset");
_Static_assert(offsetof(B3VehicleRetail, racecar_class_1920) == 0x1920,
               "racecar_class_1920 moved off retail's offset");

#endif // BURNOUT3_VEHICLE_RETAIL_H
