// GENERATED by tools/gen_ai_ranges.py -- do not edit by hand.
//
// Recovered byte ranges of the AI gather structs, at retail's offsets:
//   B3AiCar   -> the racecar object            (RC + off)
//   B3AiState -> the AI object EMBEDDED in it   (RC + 0x1A00 + off)
//
// The navigator ctor FUN_001705F0 writes the aggregate back-pointers at
// racecar+0x1A04/0x21A0/0x2160, which is what places the AI object at
// racecar+0x1A00. Its offsets are AI-relative, so the bias is applied at
// the transfer, not baked into the struct.
// The vehicle side needs no table here: the driver writes the physics
// vehicle directly, so B3_VEHICLE_RANGES carries it.
// Built from the parity assertions so they cannot drift from the structs.
#ifndef BURNOUT3_AI_RANGES_H
#define BURNOUT3_AI_RANGES_H

#include <stddef.h>
#include "burnout3_ai.h"
#include "burnout3_vehicle_sim.h"

typedef struct { unsigned off, len; } B3AiRange;

#define B3_AICAR_LEN(f) ((unsigned)sizeof(((B3AiCar*)0)->f))
static const B3AiRange B3_AICAR_RANGES[] = {
    { (unsigned)offsetof(B3AiCar, right), B3_AICAR_LEN(right) },
    { (unsigned)offsetof(B3AiCar, fwd), B3_AICAR_LEN(fwd) },
    { (unsigned)offsetof(B3AiCar, pos), B3_AICAR_LEN(pos) },
    { (unsigned)offsetof(B3AiCar, boosting), B3_AICAR_LEN(boosting) },
    { (unsigned)offsetof(B3AiCar, commit_boost), B3_AICAR_LEN(commit_boost) },
    { (unsigned)offsetof(B3AiCar, boost_ramp_done), B3_AICAR_LEN(boost_ramp_done) },
    { (unsigned)offsetof(B3AiCar, traffic_class), B3_AICAR_LEN(traffic_class) },
    { (unsigned)offsetof(B3AiCar, crash_timer), B3_AICAR_LEN(crash_timer) },
    { (unsigned)offsetof(B3AiCar, race_mode), B3_AICAR_LEN(race_mode) },
    { (unsigned)offsetof(B3AiCar, attack_active), B3_AICAR_LEN(attack_active) },
    { (unsigned)offsetof(B3AiCar, brake_suppressed), B3_AICAR_LEN(brake_suppressed) },
    { (unsigned)offsetof(B3AiCar, ooc_mode), B3_AICAR_LEN(ooc_mode) },
    { (unsigned)offsetof(B3AiCar, attack_left), B3_AICAR_LEN(attack_left) },
    { (unsigned)offsetof(B3AiCar, attack_right), B3_AICAR_LEN(attack_right) },
    { (unsigned)offsetof(B3AiCar, attack_commit), B3_AICAR_LEN(attack_commit) },
    { (unsigned)offsetof(B3AiCar, wants_boost), B3_AICAR_LEN(wants_boost) },
    { (unsigned)offsetof(B3AiCar, free_speed_floor), B3_AICAR_LEN(free_speed_floor) },
};
#define B3_AICAR_RANGES_COUNT (sizeof(B3_AICAR_RANGES)/sizeof(B3_AICAR_RANGES[0]))

#define B3_AISTATE_LEN(f) ((unsigned)sizeof(((B3AiState*)0)->f))
static const B3AiRange B3_AISTATE_RANGES[] = {
    { (unsigned)offsetof(B3AiState, target_mode), B3_AISTATE_LEN(target_mode) },
    { (unsigned)offsetof(B3AiState, boost_scale_flag), B3_AISTATE_LEN(boost_scale_flag) },
    { (unsigned)offsetof(B3AiState, des_dir), B3_AISTATE_LEN(des_dir) },
    { (unsigned)offsetof(B3AiState, max_speed), B3_AISTATE_LEN(max_speed) },
    { (unsigned)offsetof(B3AiState, time_to_target), B3_AISTATE_LEN(time_to_target) },
    { (unsigned)offsetof(B3AiState, des_dir_n), B3_AISTATE_LEN(des_dir_n) },
    { (unsigned)offsetof(B3AiState, target_angle), B3_AISTATE_LEN(target_angle) },
    { (unsigned)offsetof(B3AiState, target_speed), B3_AISTATE_LEN(target_speed) },
    { (unsigned)offsetof(B3AiState, t2t_snap), B3_AISTATE_LEN(t2t_snap) },
    { (unsigned)offsetof(B3AiState, prev_angle), B3_AISTATE_LEN(prev_angle) },
    { (unsigned)offsetof(B3AiState, corner_speed), B3_AISTATE_LEN(corner_speed) },
    { (unsigned)offsetof(B3AiState, steer_err), B3_AISTATE_LEN(steer_err) },
    { (unsigned)offsetof(B3AiState, catchup_bonus), B3_AISTATE_LEN(catchup_bonus) },
    { (unsigned)offsetof(B3AiState, pace_aggression), B3_AISTATE_LEN(pace_aggression) },
    { (unsigned)offsetof(B3AiState, pace_e4), B3_AISTATE_LEN(pace_e4) },
    { (unsigned)offsetof(B3AiState, catchup_window), B3_AISTATE_LEN(catchup_window) },
    { (unsigned)offsetof(B3AiState, pace_ec), B3_AISTATE_LEN(pace_ec) },
    { (unsigned)offsetof(B3AiState, pace_f0), B3_AISTATE_LEN(pace_f0) },
    { (unsigned)offsetof(B3AiState, pace_f4), B3_AISTATE_LEN(pace_f4) },
    { (unsigned)offsetof(B3AiState, pace_mode), B3_AISTATE_LEN(pace_mode) },
    { (unsigned)offsetof(B3AiState, pace_a04), B3_AISTATE_LEN(pace_a04) },
    { (unsigned)offsetof(B3AiState, speed_cap), B3_AISTATE_LEN(speed_cap) },
    { (unsigned)offsetof(B3AiState, catchup_gate), B3_AISTATE_LEN(catchup_gate) },
    { (unsigned)offsetof(B3AiState, catchup_expired), B3_AISTATE_LEN(catchup_expired) },
};
#define B3_AISTATE_RANGES_COUNT (sizeof(B3_AISTATE_RANGES)/sizeof(B3_AISTATE_RANGES[0]))

// The vehicle fields FUN_00105340 actually reads and writes.
#define B3_AIVEH_LEN(f) ((unsigned)sizeof(((B3VehicleFull*)0)->f))
static const B3AiRange B3_AIVEH_RANGES[] = {
    { (unsigned)offsetof(B3VehicleFull, rb.vel), B3_AIVEH_LEN(rb.vel) },
    { (unsigned)offsetof(B3VehicleFull, rb.dir), B3_AIVEH_LEN(rb.dir) },
    { (unsigned)offsetof(B3VehicleFull, rb.omega), B3_AIVEH_LEN(rb.omega) },
    { (unsigned)offsetof(B3VehicleFull, lsdm_limit_13AC), B3_AIVEH_LEN(lsdm_limit_13AC) },
    { (unsigned)offsetof(B3VehicleFull, trans.change_up_rpm), B3_AIVEH_LEN(trans.change_up_rpm) },
    { (unsigned)offsetof(B3VehicleFull, trans.omega), B3_AIVEH_LEN(trans.omega) },
    { (unsigned)offsetof(B3VehicleFull, lsdm_active_1550), B3_AIVEH_LEN(lsdm_active_1550) },
    { (unsigned)offsetof(B3VehicleFull, trans.gear), B3_AIVEH_LEN(trans.gear) },
    { (unsigned)offsetof(B3VehicleFull, drift_state_1524), B3_AIVEH_LEN(drift_state_1524) },
    { (unsigned)offsetof(B3VehicleFull, authority_1534), B3_AIVEH_LEN(authority_1534) },
    { (unsigned)offsetof(B3VehicleFull, steer_1408), B3_AIVEH_LEN(steer_1408) },
    { (unsigned)offsetof(B3VehicleFull, input_bits_13FC), B3_AIVEH_LEN(input_bits_13FC) },
    { (unsigned)offsetof(B3VehicleFull, throttle_1400), B3_AIVEH_LEN(throttle_1400) },
    { (unsigned)offsetof(B3VehicleFull, brake_1404), B3_AIVEH_LEN(brake_1404) },
    { (unsigned)offsetof(B3VehicleFull, throttle_raw_1414), B3_AIVEH_LEN(throttle_raw_1414) },
    { (unsigned)offsetof(B3VehicleFull, stop_flag_1552), B3_AIVEH_LEN(stop_flag_1552) },
    { (unsigned)offsetof(B3VehicleFull, prev_throttle_156C), B3_AIVEH_LEN(prev_throttle_156C) },
    { (unsigned)offsetof(B3VehicleFull, brake_hold_1570), B3_AIVEH_LEN(brake_hold_1570) },
    { (unsigned)offsetof(B3VehicleFull, dither_1574), B3_AIVEH_LEN(dither_1574) },
    { (unsigned)offsetof(B3VehicleFull, stuck_arm_1578), B3_AIVEH_LEN(stuck_arm_1578) },
    { (unsigned)offsetof(B3VehicleFull, reverse_timer_157C), B3_AIVEH_LEN(reverse_timer_157C) },
};
#define B3_AIVEH_RANGES_COUNT (sizeof(B3_AIVEH_RANGES)/sizeof(B3_AIVEH_RANGES[0]))


// Retail embeds the AI object here; see FUN_001705F0.
#define B3_AI_OBJECT_OFFSET 0x1A00u
#endif // BURNOUT3_AI_RANGES_H
