// RUNTIME per-track AI PACE RECORDS.
//
// Replaces the compiled-in src/burnout3_ai_pace.h, which tools/gen_ai_pace.py
// generated by walking every shipped Gamedata.bgd and baking 221 events x 6
// slots of GAME DATA into the C source.  Every consumer name below keeps its
// old spelling, so call sites are unchanged -- only the STORAGE moves, from a
// const array chosen at compile time to a table filled at startup from
//
//     build/tracks/<track>/pace.bin              ('B3PC', version 1)
//
// which tools/cextract's `pace` stage writes for all 36 shipped tracks (same
// pipeline as route.bin / grid.bin / traffic.bin).  Byte-for-byte agreement
// with gen_ai_pace.py's decode is asserted by tools/validate_no_baked_data.py.
// No per-track constant appears in this file: the caps are format limits and
// the track comes from B3_TRACK.
//
// ============================================================ PROVENANCE [C]
// The rubber band is event DATA, not a constant.  The consumer is
// FUN_00172870 @0x001728DD, the AI navigator's pace-record reader:
//
//     rec = DAT_0073A170 + grid_slot * 0x98        ; @0x00172937 imul 0x98
//     AI+0x9E4 = rec[0x97] * 0.01
//     AI+0x9E8 = rec[0x93] * 0.01   <- the CATCH-UP WINDOW, the fraction of
//                                      the race FUN_001734C0 stays armed for
//     AI+0x9EC = rec[0x90] * 0.01   <- aggression, also copied to AI+0x9E0
//     AI+0x9F0 = rec[0x92] * 0.01
//     AI+0x9F4 = rec[0x91] * 0.01
//     AI+0x9F8 = (s8) rec[0x95]
//     AI+0xA12 = (rec[0x96] & 1) == 1
//
// with the base installed by the .bgd loader FUN_0018B250 @0x0018B478 (the
// event's 0x800-byte param record) and the opponent count at param+0x3B4
// @0x0018B48A.  rec+0x94 is read by no retail path and is carried verbatim.
// The lap count in the same record (param+0x3B8, RE_BGD 3) rides along in
// pace.bin, which is what frees the track-select table of its `laps` column.
//
// ====================================================== ONE DEFECT FIXED [C]
// gen_ai_pace.py carried its own base-40 decoder that omitted the final
// reversal FUN_001AECC0 performs, so every event id in the generated header
// was spelled BACKWARDS ("FCRGSFFO" for OFFSGRCF).  The header was internally
// consistent, so it worked -- but B3_EVENT then meant one spelling here and
// the opposite one in tools/cextract (CXA_DEFAULT_EVENT "OFFSGRCF").  The
// runtime asset carries the id FUN_001AECC0 actually decodes, and the default
// below is the forward spelling; B3_EVENT now means the same thing on both
// sides of the pipeline.

#ifndef BURNOUT3_AI_PACE_RUNTIME_H
#define BURNOUT3_AI_PACE_RUNTIME_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define B3_AI_PACE_SLOTS 6

/* Format caps, not track data: the widest shipped Gamedata.bgd carries 18
 * event slots, of which at most 16 survive gen_ai_pace.py's param gate.  The
 * loader rejects a file that claims more rather than truncating silently. */
#define B3_AI_PACE_EVENT_MAX 64

/* The offline forward single race -- the port's default event.  FUN_001AECC0
 * spelling; .data 0x3E9CD8's mode-name table is Off + SgRc + F. */
#define B3_AI_PACE_DEFAULT_EVENT "OFFSGRCF"

typedef struct B3AiPaceRec {
    unsigned char aggression, f91, f92, catchup, raw94, mode, flags, f97;
} B3AiPaceRec;

/* One 72-byte pace.bin record, read straight off the file -- char arrays
 * rather than pointers for exactly the reason B3TrafficCarId uses them. */
typedef struct B3AiPaceEvent {
    char         id[16];     /* base-40 event id, e.g. "OFFSGRCF"        */
    unsigned int laps;       /* param+0x3B8                              */
    unsigned int n_opp;      /* param+0x3B4, retail's DAT_0073A180       */
    B3AiPaceRec  slot[B3_AI_PACE_SLOTS];
} B3AiPaceEvent;

static struct {
    char          track[64];
    int           tried;         /* a load has been attempted for `track` */
    int           count;
    B3AiPaceEvent ev[B3_AI_PACE_EVENT_MAX];
} g_ai_pace;

/* A missing pace.bin is LOUD on the race path -- it silently costs every rival
 * its catch-up licence, which is exactly the kind of thing a compiled-in table
 * used to hide.  The TRACK SELECT screen asks for the lap count of every track
 * the XBE lists, though, including ones the user has not extracted yet, so it
 * asks quietly; the selector already refuses to offer a track whose pace.bin
 * is absent. */
static int g_ai_pace_quiet;

/* build/tracks/<track>/pace.bin, 'B3PC' version 1 (tools/cextract/cx_pace.c):
 *   +0x00 char[4] 'B3PC'   +0x04 u32 version = 1
 *   +0x08 u32 event_count  +0x0C u32 slots_per_event = 6
 *   +0x10 event_count x 72-byte B3AiPaceEvent record
 * Returns the number of events loaded (0 = no usable asset). */
static int b3_ai_pace_load(const char* track) {
    struct { char magic[4]; unsigned int version, count, slots; } h;
    char path[256];
    FILE* f;

    if (!track || !*track) return 0;
    if (g_ai_pace.tried && strcmp(g_ai_pace.track, track) == 0)
        return g_ai_pace.count;

    memset(&g_ai_pace, 0, sizeof g_ai_pace);
    snprintf(g_ai_pace.track, sizeof g_ai_pace.track, "%s", track);
    g_ai_pace.tried = 1;

    snprintf(path, sizeof path, "build/tracks/%s/pace.bin", track);
    f = fopen(path, "rb");
    if (!f) {
        if (!g_ai_pace_quiet)
            fprintf(stderr, "[Burnout3] ai pace: no %s -- every rival falls "
                    "to retail's NO-RECORD branch (@0x001728F0, catch-up 0)\n",
                    path);
        return 0;
    }
    if (sizeof(B3AiPaceEvent) != 72) {
        fprintf(stderr, "[Burnout3] ai pace: B3AiPaceEvent is %d bytes, "
                "expected 72\n", (int)sizeof(B3AiPaceEvent));
        fclose(f);
        return 0;
    }
    if (fread(&h, sizeof h, 1, f) != 1
        || memcmp(h.magic, "B3PC", 4) != 0
        || h.version != 1
        || h.slots != B3_AI_PACE_SLOTS
        || h.count == 0 || h.count > B3_AI_PACE_EVENT_MAX) {
        fprintf(stderr, "[Burnout3] ai pace: %s is not a usable B3PC v1 "
                "asset\n", path);
        fclose(f);
        return 0;
    }
    if (fread(g_ai_pace.ev, sizeof(B3AiPaceEvent), h.count, f) != h.count) {
        fprintf(stderr, "[Burnout3] ai pace: %s truncated\n", path);
        fclose(f);
        memset(&g_ai_pace.ev, 0, sizeof g_ai_pace.ev);
        return 0;
    }
    fclose(f);
    {   /* the extractor NUL-pads, but never trust a file for termination */
        unsigned int k;
        for (k = 0; k < h.count; k++)
            g_ai_pace.ev[k].id[15] = '\0';
    }
    g_ai_pace.count = (int)h.count;
    return g_ai_pace.count;
}

/* FUN_00172870's lookup, minus the DAT_0073A170 indirection: the loader has
 * already chosen an event, so the port names it.  Returns NULL when the track
 * or event is unknown, which is retail's no-record branch (@0x001728F0):
 * AI+0x9E8 = 0, i.e. catch-up expires on the first frame. */
static const B3AiPaceEvent*
b3_ai_pace_find(const char* track, const char* event)
{
    int i;
    if (!track) return 0;
    if (!event || !*event) event = B3_AI_PACE_DEFAULT_EVENT;
    if (!b3_ai_pace_load(track)) return 0;
    for (i = 0; i < g_ai_pace.count; i++) {
        if (strcmp(g_ai_pace.ev[i].id, event) != 0) continue;
        printf("[Burnout3] ai pace: build/tracks/%s/pace.bin -- %d events, "
               "using %s (%u opponents, %u laps)\n",
               track, g_ai_pace.count, g_ai_pace.ev[i].id,
               g_ai_pace.ev[i].n_opp, g_ai_pace.ev[i].laps);
        return &g_ai_pace.ev[i];
    }
    fprintf(stderr, "[Burnout3] ai pace: %s has no event %s -- retail's "
            "no-record branch\n", track, event);
    return 0;
}

/* AI+0x9E8 for one grid slot.  Retail's own gate is `slot >= DAT_0073A180`
 * (@0x001728DD), the opponent count, so a slot past the field gets 0. */
static inline float b3_ai_pace_catchup_window(const B3AiPaceEvent* ev, int slot)
{
    if (!ev || slot < 0 || slot >= B3_AI_PACE_SLOTS) return 0.0f;
    if (slot >= (int)ev->n_opp) return 0.0f;
    return (float)ev->slot[slot].catchup * 0.01f;
}

/* AI+0x9EC / AI+0x9E0, the per-opponent aggression the attack machine gates on
 * ("Min. aggression before we start attacking" = 0.002). */
static inline float b3_ai_pace_aggression(const B3AiPaceEvent* ev, int slot)
{
    if (!ev || slot < 0 || slot >= B3_AI_PACE_SLOTS) return 0.0f;
    if (slot >= (int)ev->n_opp) return 0.0f;
    return (float)ev->slot[slot].aggression * 0.01f;
}

/* The event's LAP COUNT, param+0x3B8 (RE_BGD 3) -- the number the track-select
 * screen shows and the race runs to.  0 when the track or event has no record;
 * quiet, because the selector asks it once per offered track. */
static int b3_ai_pace_laps(const char* track, const char* event)
{
    int i, loaded;
    if (!track) return 0;
    if (!event || !*event) event = B3_AI_PACE_DEFAULT_EVENT;
    g_ai_pace_quiet = 1;
    loaded = b3_ai_pace_load(track);
    g_ai_pace_quiet = 0;
    if (!loaded) return 0;
    for (i = 0; i < g_ai_pace.count; i++)
        if (strcmp(g_ai_pace.ev[i].id, event) == 0)
            return (int)g_ai_pace.ev[i].laps;
    return 0;
}

#endif /* BURNOUT3_AI_PACE_RUNTIME_H */
