// Generated by tools/extract_physics_params.py -- do not edit by hand.
// Burnout 3 vehicle physics parameter table, recovered from the
// registration function at 0x00132D10. Offsets are byte offsets into the
// game's per-vehicle physics struct; all fields are f32.
#ifndef BURNOUT3_PHYSICS_PARAMS_H
#define BURNOUT3_PHYSICS_PARAMS_H

typedef struct {
    const char* group;
    const char* name;
    unsigned    offset;   // byte offset into the 0x1D0-byte physics struct
    float       def;      // compiled-in default (FUN_00132950)
    int         has_def;
} PhysicsParam;

#define PHYSICS_PARAM_COUNT 64

static const PhysicsParam PHYSICS_PARAMS[PHYSICS_PARAM_COUNT] = {
    /* Physics/Aggressive Driving Reaction */
    { "Physics/Aggressive Driving Reaction", "Steer Away Time (s)", 0x1BCu, 0.300000012f, 1 },
    { "Physics/Aggressive Driving Reaction", "Total Out-Of-Control Time (s)", 0x1C0u, 1.0f, 1 },
    { "Physics/Aggressive Driving Reaction", "Steering Max Angle (degrees)", 0x1C4u, 24.0f, 1 },
    { "Physics/Aggressive Driving Reaction", "Steering Max Velocity", 0x1C8u, 50.0f, 1 },
    { "Physics/Aggressive Driving Reaction", "Steering Drag Coef", 0x1CCu, 0.5f, 1 },
    /* Physics/Drift */
    { "Physics/Drift", "Slide Max", 0x160u, 0.850000024f, 1 },
    { "Physics/Drift", "Slide Min", 0x164u, 0.75f, 1 },
    { "Physics/Drift", "Turn Momentum Slow", 0x168u, 800.0f, 1 },
    { "Physics/Drift", "Turn Momentum Fast", 0x16Cu, 1100.0f, 1 },
    { "Physics/Drift", "Auto Drift Delay", 0x170u, 0.769999981f, 1 },
    { "Physics/Drift", "Turn Rate", 0x174u, 1.20000005f, 1 },
    { "Physics/Drift", "Min Drift Speed", 0x194u, 65.0f, 1 },
    { "Physics/Drift", "Max Speed Pressure", 0x198u, 0.5f, 1 },
    { "Physics/Drift", "Max Drift Angle", 0x1A0u, 45.0f, 1 },
    /* Physics/Race Car/Body Roll */
    { "Physics/Race Car/Body Roll", "Brake Force Height", 0x138u, -0.550000012f, 1 },
    { "Physics/Race Car/Body Roll", "Accel Force Height", 0x13Cu, -0.349999994f, 1 },
    { "Physics/Race Car/Body Roll", "Steer Force Height", 0x140u, -0.219999999f, 1 },
    { "Physics/Race Car/Body Roll", "Drift Force Height", 0x144u, -0.230000004f, 1 },
    /* Physics/Race Car/LSDM */
    { "Physics/Race Car/LSDM", "Speed Limit", 0x17Cu, 35.0f, 1 },
    { "Physics/Race Car/LSDM", "Steering Angle", 0x180u, 50.0f, 1 },
    { "Physics/Race Car/LSDM", "Torque 1", 0x184u, 1.0f, 1 },
    { "Physics/Race Car/LSDM", "Torque 2", 0x188u, 0.899999976f, 1 },
    /* Physics/Race Car/Misc */
    { "Physics/Race Car/Misc", "Drag Coef", 0x130u, 1.89999998f, 1 },
    { "Physics/Race Car/Misc", "Downforce Coef", 0x134u, 0.0f, 1 },
    { "Physics/Race Car/Misc", "Braking Factor", 0x15Cu, 2.0f, 1 },
    { "Physics/Race Car/Misc", "Wall Collsion Penalty", 0x178u, 0.99000001f, 1 },
    { "Physics/Race Car/Misc", "Accel Multiplier", 0x18Cu, 4.0f, 1 },
    { "Physics/Race Car/Misc", "Engine Braking Factor", 0x19Cu, -5500.0f, 1 },
    { "Physics/Race Car/Misc", "Max Speed In Boost", 0x1A4u, 141.0f, 1 },
    { "Physics/Race Car/Misc", "In Air Corkscrew Damping", 0x1B0u, 0.800000012f, 1 },
    { "Physics/Race Car/Misc", "Min Drift Angle In Air", 0x1B4u, 5.0f, 1 },
    /* Physics/Steering */
    { "Physics/Steering", "Min Angle (degrees)", 0x148u, 10.5f, 1 },
    { "Physics/Steering", "Max Angle (degrees)", 0x14Cu, 14.0f, 1 },
    { "Physics/Steering", "Min Velocity", 0x150u, 23.0f, 1 },
    { "Physics/Steering", "Max Velocity", 0x154u, 12.0f, 1 },
    { "Physics/Steering", "Response", 0x158u, 0.158000007f, 1 },
    { "Physics/Steering", "Drag Coef", 0x190u, 2.0f, 1 },
    /* Physics/Suspension/Front */
    { "Physics/Suspension/Front", "Attatch Height", 0x0BCu, 0.100000001f, 1 },
    { "Physics/Suspension/Front", "Spring Force", 0x0C0u, 60000.0f, 1 },
    { "Physics/Suspension/Front", "Spring Damping", 0x0C4u, 5000.0f, 1 },
    { "Physics/Suspension/Front", "Spring Length", 0x0C8u, 0.200000003f, 1 },
    /* Physics/Suspension/Rear */
    { "Physics/Suspension/Rear", "Spring Force", 0x0CCu, 60000.0f, 1 },
    { "Physics/Suspension/Rear", "Spring Damping", 0x0D0u, 5000.0f, 1 },
    { "Physics/Suspension/Rear", "Spring Length", 0x0D4u, 0.200000003f, 1 },
    { "Physics/Suspension/Rear", "Attatch Height", 0x0D8u, 0.100000001f, 1 },
    /* Physics/Transmission/Boost Kick */
    { "Physics/Transmission/Boost Kick", "Boost Kick Torque", 0x128u, 2.0f, 1 },
    { "Physics/Transmission/Boost Kick", "Boost Kick Time", 0x12Cu, 1.0f, 1 },
    /* Physics/Transmission/Engine */
    { "Physics/Transmission/Engine", "Idle RPM", 0x104u, 1000.0f, 1 },
    { "Physics/Transmission/Engine", "Change Up RPM", 0x108u, 6800.0f, 1 },
    { "Physics/Transmission/Engine", "Change Down RPM", 0x10Cu, 4200.0f, 1 },
    { "Physics/Transmission/Engine", "Max RPM", 0x118u, 6800.0f, 1 },
    { "Physics/Transmission/Engine", "Torque", 0x11Cu, 630.0f, 1 },
    { "Physics/Transmission/Engine", "Peak Torque Revs", 0x120u, 5000.0f, 1 },
    { "Physics/Transmission/Engine", "Fall Off Torque Revs", 0x124u, 6500.0f, 1 },
    /* Physics/Transmission/Gear Ratios */
    { "Physics/Transmission/Gear Ratios", "Reverse", 0x0E0u, -1.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "Neutral", 0x0E4u, 0.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "1st Gear", 0x0E8u, 5.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "2nd Gear", 0x0ECu, 5.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "3rd Gear", 0x0F0u, 5.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "4th Gear", 0x0F4u, 5.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "5th Gear", 0x0F8u, 5.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "6th Gear", 0x0FCu, 5.0f, 1 },
    { "Physics/Transmission/Gear Ratios", "Final Gear", 0x100u, 5.0f, 1 },
    /* Physics/Vehicle */
    { "Physics/Vehicle", "Mass (Kg)", 0x0B8u, 1000.0f, 1 },
};

#define B3_PHYSICS_STRUCT_SIZE 0x1D0u

// Field offsets, for direct access into the physics struct.
#define B3_PHYS_VEHICLE_MASS_KG                    0x0B8u
#define B3_PHYS_FRONT_ATTATCH_HEIGHT               0x0BCu
#define B3_PHYS_FRONT_SPRING_FORCE                 0x0C0u
#define B3_PHYS_FRONT_SPRING_DAMPING               0x0C4u
#define B3_PHYS_FRONT_SPRING_LENGTH                0x0C8u
#define B3_PHYS_REAR_SPRING_FORCE                  0x0CCu
#define B3_PHYS_REAR_SPRING_DAMPING                0x0D0u
#define B3_PHYS_REAR_SPRING_LENGTH                 0x0D4u
#define B3_PHYS_REAR_ATTATCH_HEIGHT                0x0D8u
#define B3_PHYS_GEAR_RATIOS_REVERSE                0x0E0u
#define B3_PHYS_GEAR_RATIOS_NEUTRAL                0x0E4u
#define B3_PHYS_GEAR_RATIOS_1ST_GEAR               0x0E8u
#define B3_PHYS_GEAR_RATIOS_2ND_GEAR               0x0ECu
#define B3_PHYS_GEAR_RATIOS_3RD_GEAR               0x0F0u
#define B3_PHYS_GEAR_RATIOS_4TH_GEAR               0x0F4u
#define B3_PHYS_GEAR_RATIOS_5TH_GEAR               0x0F8u
#define B3_PHYS_GEAR_RATIOS_6TH_GEAR               0x0FCu
#define B3_PHYS_GEAR_RATIOS_FINAL_GEAR             0x100u
#define B3_PHYS_ENGINE_IDLE_RPM                    0x104u
#define B3_PHYS_ENGINE_CHANGE_UP_RPM               0x108u
#define B3_PHYS_ENGINE_CHANGE_DOWN_RPM             0x10Cu
#define B3_PHYS_ENGINE_MAX_RPM                     0x118u
#define B3_PHYS_ENGINE_TORQUE                      0x11Cu
#define B3_PHYS_ENGINE_PEAK_TORQUE_REVS            0x120u
#define B3_PHYS_ENGINE_FALL_OFF_TORQUE_REVS        0x124u
#define B3_PHYS_BOOST_KICK_BOOST_KICK_TORQUE       0x128u
#define B3_PHYS_BOOST_KICK_BOOST_KICK_TIME         0x12Cu
#define B3_PHYS_MISC_DRAG_COEF                     0x130u
#define B3_PHYS_MISC_DOWNFORCE_COEF                0x134u
#define B3_PHYS_BODY_ROLL_BRAKE_FORCE_HEIGHT       0x138u
#define B3_PHYS_BODY_ROLL_ACCEL_FORCE_HEIGHT       0x13Cu
#define B3_PHYS_BODY_ROLL_STEER_FORCE_HEIGHT       0x140u
#define B3_PHYS_BODY_ROLL_DRIFT_FORCE_HEIGHT       0x144u
#define B3_PHYS_STEERING_MIN_ANGLE_DEGREES         0x148u
#define B3_PHYS_STEERING_MAX_ANGLE_DEGREES         0x14Cu
#define B3_PHYS_STEERING_MIN_VELOCITY              0x150u
#define B3_PHYS_STEERING_MAX_VELOCITY              0x154u
#define B3_PHYS_STEERING_RESPONSE                  0x158u
#define B3_PHYS_MISC_BRAKING_FACTOR                0x15Cu
#define B3_PHYS_DRIFT_SLIDE_MAX                    0x160u
#define B3_PHYS_DRIFT_SLIDE_MIN                    0x164u
#define B3_PHYS_DRIFT_TURN_MOMENTUM_SLOW           0x168u
#define B3_PHYS_DRIFT_TURN_MOMENTUM_FAST           0x16Cu
#define B3_PHYS_DRIFT_AUTO_DRIFT_DELAY             0x170u
#define B3_PHYS_DRIFT_TURN_RATE                    0x174u
#define B3_PHYS_MISC_WALL_COLLSION_PENALTY         0x178u
#define B3_PHYS_LSDM_SPEED_LIMIT                   0x17Cu
#define B3_PHYS_LSDM_STEERING_ANGLE                0x180u
#define B3_PHYS_LSDM_TORQUE_1                      0x184u
#define B3_PHYS_LSDM_TORQUE_2                      0x188u
#define B3_PHYS_MISC_ACCEL_MULTIPLIER              0x18Cu
#define B3_PHYS_STEERING_DRAG_COEF                 0x190u
#define B3_PHYS_DRIFT_MIN_DRIFT_SPEED              0x194u
#define B3_PHYS_DRIFT_MAX_SPEED_PRESSURE           0x198u
#define B3_PHYS_MISC_ENGINE_BRAKING_FACTOR         0x19Cu
#define B3_PHYS_DRIFT_MAX_DRIFT_ANGLE              0x1A0u
#define B3_PHYS_MISC_MAX_SPEED_IN_BOOST            0x1A4u
#define B3_PHYS_MISC_IN_AIR_CORKSCREW_DAMPING      0x1B0u
#define B3_PHYS_MISC_MIN_DRIFT_ANGLE_IN_AIR        0x1B4u
#define B3_PHYS_AGGRESSIVE_DRIVING_REACTION_STEER_AWAY_TIME_S 0x1BCu
#define B3_PHYS_AGGRESSIVE_DRIVING_REACTION_TOTAL_OUT_OF_CONTROL_TIME_S 0x1C0u
#define B3_PHYS_AGGRESSIVE_DRIVING_REACTION_STEERING_MAX_ANGLE_DEGREES 0x1C4u
#define B3_PHYS_AGGRESSIVE_DRIVING_REACTION_STEERING_MAX_VELOCITY 0x1C8u
#define B3_PHYS_AGGRESSIVE_DRIVING_REACTION_STEERING_DRAG_COEF 0x1CCu

#endif // BURNOUT3_PHYSICS_PARAMS_H
